-- New York — Additional Locations
-- Skips existing: Bemelmans Bar at The Carlyle, The Mark Hotel, The Frick Collection,
--   Bergdorf Goodman, Balthazar, The Polo Bar, The Odeon
-- Adds 38 new locations.

INSERT INTO locations (city_id, name, neighborhood, category, description, latitude, longitude, photo_url, vibe_difficulty, what_to_wear, is_approved) VALUES

-- 1. The Plaza Hotel
('11111111-0000-0000-0000-000000000001',
'The Plaza Hotel',
'Midtown',
'Hotel Lobby',
'There is no more loaded address in New York than the southeast corner of Central Park. Eloise lived here. Cary Grant fled assassins here. The lobby is a gilded holding pen for the quietly famous, the obviously rich, and the people who want to feel what that feels like for the price of an afternoon tea. Sit in the Palm Court, order something in a flute, and hold it as though you are accustomed to holding things in flutes.',
40.7646310, -73.9743240,
NULL,
4,
'{"men": {"brands": ["Brioni", "Kiton", "Patek Philippe", "John Lobb"], "outfit": {"top": "Pale grey or cream sport coat, white shirt open at the collar", "bottom": "Charcoal flannel trousers with a clean break", "shoes": "Black or chestnut cap-toe Oxfords, highly polished", "bag": "Slim leather document holder or nothing at all", "accessories": "Patek Philippe or vintage Rolex, no other jewelry, pocket square in ivory linen"}, "color_palette": "Charcoal, cream, ivory — the palette of a man who once owned a racehorse without mentioning it", "budget_dupe": "A well-pressed suit from J.Crew or SuitSupply in grey, resoled leather shoes. The Plaza lobby is dark enough for ambition to pass as breeding."}, "women": {"brands": ["Oscar de la Renta", "The Row", "Cartier", "Manolo Blahnik"], "outfit": {"top": "Structured blazer in ivory or pale blush, or a silk blouse in cream with pearl buttons", "bottom": "Tailored wide-leg trousers in champagne or cream", "shoes": "Pointed-toe kitten heel in nude or black", "bag": "Structured top-handle in black or tan, no visible logos", "accessories": "Cartier Love bracelet, pearl drop earrings, single delicate gold chain"}, "color_palette": "Ivory, champagne, nude, blush — afternoon tea at the most famous hotel in America", "budget_dupe": "Banana Republic blazer in cream, well-cut trousers from COS, one serious secondhand bag from a consignment shop. You are doing afternoon tea, not the Met Gala."}}',
true),

-- 2. The St. Regis New York
('11111111-0000-0000-0000-000000000001',
'The St. Regis New York',
'Midtown',
'Continental',
'John Jacob Astor IV built this hotel in 1904 and it has never fully recovered from having good taste. The King Cole Bar — with its Maxfield Parrish mural of Old King Cole — is one of the few places in Manhattan where you can order a Bloody Mary with the sincere belief that it was invented here. The butler service still exists. The room still matters. Order something red, look at the mural, and try to look unsurprised.',
40.7613000, -73.9744530,
NULL,
4,
'{"men": {"brands": ["Tom Ford", "Huntsman", "A. Lange & Söhne", "Crockett & Jones"], "outfit": {"top": "Midnight navy suit with a faint chalk stripe, or a charcoal blazer with white shirt", "bottom": "Matching trousers, full break, nothing modern", "shoes": "Black cap-toe Oxfords or dark burgundy loafers with tassels", "bag": "Nothing. Possibly an overcoat over one arm.", "accessories": "A. Lange & Söhne or Jaeger-LeCoultre, silk pocket square in ivory or pale gold"}, "color_palette": "Midnight navy, charcoal, ivory — the palette of someone who considers a Bloody Mary a medical prescription", "budget_dupe": "A good suit from SuitSupply in navy or charcoal. The King Cole Bar is lit for maximum atmosphere and minimum scrutiny. Fit matters more than label."}, "women": {"brands": ["Valentino", "Carolina Herrera", "Van Cleef & Arpels", "Roger Vivier"], "outfit": {"top": "Silk blouse in dusty rose or champagne, or a shift dress in pale gold", "bottom": "Straight-leg cigarette trousers or an A-line midi skirt in deep ivory", "shoes": "Block-heel court shoe in black or nude, or an embellished flat for afternoon", "bag": "Small structured top-handle or a beaded evening clutch if after 7pm", "accessories": "Van Cleef Alhambra or a serious vintage brooch, pearl earrings, a single thin bracelet"}, "color_palette": "Dusty rose, champagne, pale gold — someone who found this hotel in a novel and has never fully left", "budget_dupe": "A good silk blouse from Equipment or a vintage find, clean trousers from & Other Stories. The Maxfield Parrish mural is the most valuable thing in the room — stand near it."}}',
true),

-- 3. The Carlyle Hotel
('11111111-0000-0000-0000-000000000001',
'The Carlyle Hotel',
'Upper East Side',
'Old Money',
'The Carlyle is not a hotel in the ordinary sense. It is a residential building that tolerates guests. World leaders have stayed here. JFK had a permanent suite. The Café Carlyle runs one of the last great cabaret programs in America. Even if you''re only walking through the lobby, you will feel a quality of hush that only comes from decades of important people having private conversations in upholstered chairs.',
40.7743370, -73.9631320,
NULL,
5,
'{"men": {"brands": ["Brioni", "Huntsman Savile Row", "Patek Philippe", "Lobb"], "outfit": {"top": "Dark navy double-breasted blazer or a charcoal suit — this is a proper dress code building", "bottom": "Matching or coordinated trousers, perfectly pressed", "shoes": "Black cap-toes or dark Oxford, mirror shine", "bag": "Nothing or a slim leather attaché", "accessories": "Patek Philippe Calatrava in yellow gold, silk pocket square in deep burgundy, nothing else"}, "color_palette": "Dark navy, charcoal, black, ivory — the palette of a man who has attended events he cannot discuss", "budget_dupe": "SuitSupply Napoli in charcoal. You are walking through one of the most serious lobbies in New York. Buy one good suit and mean it."}, "women": {"brands": ["The Row", "Bottega Veneta", "Cartier", "Manolo Blahnik"], "outfit": {"top": "Long-sleeve silk dress in midnight blue or deep emerald, or a cashmere blazer over wide-leg trousers", "bottom": "Tailored wide-leg trousers in charcoal or a structured midi skirt", "shoes": "Classic pointed-toe heel in black or navy, no platforms", "bag": "Bottega Veneta Jodie or a small structured Kelly-style bag — no visible branding", "accessories": "Cartier Trinity ring or thin gold chain, small diamond studs, possibly gloves in cool weather"}, "color_palette": "Midnight blue, deep emerald, charcoal — someone whose composure is structural, not performed", "budget_dupe": "A well-cut dress from Theory or Vince in a dark solid colour. The Carlyle rewards restraint at every price point."}}',
true),

-- 4. Baccarat Hotel & Residences
('11111111-0000-0000-0000-000000000001',
'Baccarat Hotel New York',
'Midtown',
'Hotel Lobby',
'The most crystalline hotel in the city — 4,500 pieces of Baccarat crystal deployed without a hint of apology. The lobby bar is genuinely one of the most beautiful rooms in Midtown, which is a low bar until you see it and revise your opinion upward. The Grand Salon has the quality of light that makes everyone look slightly more important than they are. Use it accordingly.',
40.7595500, -73.9740300,
NULL,
4,
'{"men": {"brands": ["Zegna", "Tom Ford", "IWC", "Berluti"], "outfit": {"top": "Light grey or cream sport coat, white or pale blue shirt, no tie", "bottom": "Dark navy or charcoal trousers, slim cut", "shoes": "Berluti or Edward Green in cognac or tan", "bag": "Nothing, or a very slim leather card holder", "accessories": "IWC Portugieser or Cartier Santos, no other jewelry, perhaps a pocket square in crystal blue to acknowledge where you are"}, "color_palette": "Crystal clear, silver-grey, cream — the palette of someone who appreciates things that refract light", "budget_dupe": "A clean fitted blazer in light grey from Theory or COS. The crystal does the heavy lifting in this room — you just need to not clash with it."}, "women": {"brands": ["Celine", "Saint Laurent", "Messika", "Aquazzura"], "outfit": {"top": "A slip dress in champagne or silver, or a structured blazer over wide-leg silk trousers", "bottom": "High-waisted silk trousers in ivory or pale grey", "shoes": "Strappy heeled sandal in metallic or nude", "bag": "Celine clutch or small Saint Laurent Lou in silver", "accessories": "Messika diamond ear cuffs, thin silver or gold chain, understated is the only mode"}, "color_palette": "Champagne, silver, crystal white — someone who is not trying to compete with 4,500 pieces of Baccarat crystal (you will lose)", "budget_dupe": "A silk or satin slip dress from & Other Stories in champagne. Simple metallic accessories. The room will elevate you further than your budget can."}}',
true),

-- 5. Aman New York
('11111111-0000-0000-0000-000000000001',
'Aman New York',
'Midtown',
'Hotel Lobby',
'Aman took the top six floors of the Crown Building — one of the most significant Beaux Arts structures on Fifth Avenue — and turned it into the most expensive hotel in the city with barely a whisper. The aesthetic is stripped-down grandeur: marble floors, wood paneling, almost no signage. The bar and restaurant are members-club adjacent. If you have to ask what things cost here, you are still the target demographic but might want to sit down first.',
40.7618000, -73.9753000,
NULL,
5,
'{"men": {"brands": ["Loro Piana", "Brunello Cucinelli", "Rolex", "Berluti"], "outfit": {"top": "Cashmere crewneck in mushroom or stone, or a fine linen shirt in off-white — no tie, no blazer required", "bottom": "Stone or camel straight-leg trousers, impeccably pressed", "shoes": "Clean unbranded loafers in suede or minimal leather sneakers (Loro Piana or Common Projects)", "bag": "Nothing, or a very quiet leather portfolio", "accessories": "Rolex Datejust or Day-Date if you have it — the only acceptable ostentation here"}, "color_palette": "Stone, mushroom, camel, off-white — the palette of someone who finds conspicuous consumption gauche", "budget_dupe": "Uniqlo cashmere in a muted neutral, COS trousers in stone. Aman''s entire philosophy is about removing visual noise. Your wallet size is less important than your ability to be quiet about it."}, "women": {"brands": ["The Row", "Loro Piana", "Cartier", "Bottega Veneta"], "outfit": {"top": "Long-sleeve The Row cashmere in stone or cream, or a loose linen tunic", "bottom": "Wide-leg trousers in oatmeal or pale sand", "shoes": "Clean leather loafers or minimal slides", "bag": "Bottega Veneta Cassette in camel or cloud grey", "accessories": "Cartier Love bracelet, simple gold studs, nothing louder than a whisper"}, "color_palette": "Oatmeal, sand, camel, pale stone — the palette of someone who owns property in multiple time zones and never mentions it", "budget_dupe": "Toteme or COS for the neutrals. One really good bag borrowed or secondhand. Aman''s clientele has impeccable taste and zero desire to show off — match the energy, not the price tag."}}',
true),

-- 6. The Beekman Hotel
('11111111-0000-0000-0000-000000000001',
'The Beekman Hotel',
'Financial District',
'Hotel Lobby',
'A restored 1883 neo-Gothic tower in the Financial District with a nine-story atrium that is one of the most architecturally significant interiors in New York. The atrium lobby looks like someone took a Victorian birdcage and filled it with good taste. Tom Colicchio''s restaurant occupies the ground floor. The crowd is media, finance, and the occasional academic who can''t believe this exists downtown.',
40.7117000, -74.0059000,
NULL,
3,
'{"men": {"brands": ["A.P.C.", "Acne Studios", "Swatch x Blancpain", "Common Projects"], "outfit": {"top": "Dark navy or forest green chore coat, or a heritage-weight chambray shirt", "bottom": "Dark slim-cut jeans or straight-leg chinos in olive", "shoes": "Common Projects derby or clean white leather sneakers", "bag": "Leather tote or minimalist backpack", "accessories": "Minimal watch, no flash — this crowd appreciates architecture over accessories"}, "color_palette": "Forest green, navy, charcoal, burnt sienna — the palette of someone who appreciates Victorian ironwork", "budget_dupe": "A.P.C. vibes are achievable from any good basics brand. A clean, considered outfit in dark neutrals. The building is doing most of the work here."}, "women": {"brands": ["Vince", "Theory", "Jenni Kayne", "Madewell"], "outfit": {"top": "Relaxed blazer in camel or forest green over a ribbed turtleneck", "bottom": "Dark straight-leg jeans or tailored wide-leg trousers", "shoes": "Ankle boots in cognac or clean white sneakers", "bag": "A leather bucket bag or structured tote", "accessories": "Gold stacking rings, minimal chain necklace, nothing too formal"}, "color_palette": "Camel, forest green, cognac, cream — downtown intellectual meets uptown architecture", "budget_dupe": "Gap Premium linen blazer, Levi''s straight jeans, vintage leather boots. Look like you were on your way to a gallery opening and stopped for a drink."}}',
true),

-- 7. The Bowery Hotel
('11111111-0000-0000-0000-000000000001',
'The Bowery Hotel',
'East Village',
'Hotel Lobby',
'The Bowery Hotel is what happens when someone decides to make a hotel look like it has always been there, and succeeds so completely that it becomes the realest-feeling place in the neighborhood. The lobby is all worn leather and exposed brick. The terrace bar has drawn the right kind of downtown crowd for fifteen years. Johnny Depp has stayed here. So has Patti Smith. So did the person sitting next to you, probably.',
40.7248000, -73.9915000,
NULL,
3,
'{"men": {"brands": ["Nudie Jeans", "Acne Studios", "Our Legacy", "R.M. Williams"], "outfit": {"top": "Lived-in leather jacket or a heavy cotton overshirt in olive or charcoal", "bottom": "Dark slim jeans or carpenter pants, intentionally worn", "shoes": "Chelsea boots or a clean sneaker with heritage credentials", "bag": "Canvas tote or nothing", "accessories": "A mechanical watch that looks like it was bought at a flea market (but wasn''t), simple ring"}, "color_palette": "Black, charcoal, olive, worn denim — the palette of someone who has been coming to this neighborhood since before it changed", "budget_dupe": "Levi''s, a vintage leather jacket from eBay, Chelsea boots from Thursday Boot Co. The Bowery rewards authenticity over expense."}, "women": {"brands": ["Isabel Marant", "Toteme", "Ganni", "Golden Goose"], "outfit": {"top": "Loose oversized blazer or vintage-style band tee under a structured leather jacket", "bottom": "Straight-leg jeans with a slight let-down hem, or a midi skirt in dark floral", "shoes": "Platform boots or broken-in Golden Goose sneakers (if you must)", "bag": "Leather crossbody or a soft hobo bag", "accessories": "Stacked silver rings, small hoop earrings, possibly a scarf"}, "color_palette": "Dark denim, black, rust, off-white — the palette of someone who has read all the right books about this neighborhood", "budget_dupe": "Vintage finds are the entire point here. A great vintage blazer, well-worn jeans, good boots. Downtown cool is about having a history, even if it''s borrowed."}}',
true),

-- 8. The Greenwich Hotel
('11111111-0000-0000-0000-000000000001',
'The Greenwich Hotel',
'Tribeca',
'Hotel Lobby',
'Robert De Niro''s hotel in Tribeca is one of the most genuinely comfortable boutique hotels in New York — no two rooms are alike, every surface has a provenance, and the Japanese-style pool is a legitimate secret. The lobby has the quality of a very good friend''s very grand house. Locanda Verde on the ground floor is a power breakfast destination for the film and finance overlap that defines this neighborhood.',
40.7201000, -74.0100000,
NULL,
4,
'{"men": {"brands": ["Brunello Cucinelli", "Loro Piana", "Cartier", "Aubercy"], "outfit": {"top": "Cashmere zip-neck in mid-grey or a relaxed linen shirt in white — Tribeca money dresses like it''s Saturday even on Tuesday", "bottom": "Slim dark chinos or well-cut dark jeans with a clean break", "shoes": "Loafers in suede or clean leather sneakers — nothing shiny", "bag": "Very small leather satchel or nothing", "accessories": "Cartier Santos or a discreet vintage watch, no other jewelry"}, "color_palette": "Dove grey, navy, cream, cognac — the palette of a Tribeca loft owner who chose the building before the neighborhood was safe", "budget_dupe": "Uniqlo U cashmere, dark jeans from A.P.C., good leather loafers. The Greenwich is about the quality of your nonchalance."}, "women": {"brands": ["The Row", "Vince", "Celine", "Jenni Kayne"], "outfit": {"top": "Silk or cashmere shell in ivory or camel, or a relaxed blouse in white linen", "bottom": "Wide-leg trousers in soft camel or cream, or dark straight jeans", "shoes": "Clean pointed-toe mule or minimalist loafer", "bag": "The Row bag in tan or Celine Triomphe in black — or any beautiful leather bag without logos", "accessories": "Single gold chain, simple stud earrings, a tan trench if the weather cooperates"}, "color_palette": "Ivory, camel, soft cream — Tribeca''s version of old money, which is new money that has started buying art", "budget_dupe": "COS or Arket for the basics, one great vintage find for the bag. The combination of relaxed and polished is harder than it looks and cheaper than the labels suggest."}}',
true),

-- 9. Nine Orchard
('11111111-0000-0000-0000-000000000001',
'Nine Orchard',
'Lower East Side',
'Hotel Lobby',
'A converted 1920s Lower East Side bank building that has become the most interesting hotel in downtown Manhattan. The interiors are all original stone, brass, and marble — nothing was added that wasn''t already there or didn''t belong. The ground-floor restaurant and bar have a serious art world following. The LES crowd mixes with the uptown transplants who read about it in a magazine and haven''t left.',
40.7185000, -73.9921000,
NULL,
3,
'{"men": {"brands": ["Our Legacy", "Acne Studios", "Maison Margiela", "Common Projects"], "outfit": {"top": "Deconstructed blazer in black or off-white, or a well-chosen vintage piece", "bottom": "Slim dark trousers or wide-leg cropped pants in charcoal", "shoes": "Common Projects Derby or Margiela Replica in white", "bag": "Nothing or a minimal tote", "accessories": "An interesting ring, a watch that implies research rather than expenditure"}, "color_palette": "Black, off-white, raw concrete — the palette of someone who chose this neighborhood before the hotel existed", "budget_dupe": "COS for the minimal separates. One interesting vintage or secondhand piece. The art world cares about your eye, not your budget."}, "women": {"brands": ["Bottega Veneta", "Issey Miyake", "Toteme", "Lemaire"], "outfit": {"top": "An architectural knit in ivory or stone, or a pleated Issey Miyake top", "bottom": "Wide-leg cropped trousers or a bias-cut skirt in charcoal", "shoes": "Minimalist leather loafers or strappy flat sandals", "bag": "Bottega Veneta Pouch or a deliberately interesting vintage find", "accessories": "A single statement ring, architectural earrings, nothing mass-market"}, "color_palette": "Stone, charcoal, ivory, brass — the palette of someone whose apartment is in a converted bank and has original details", "budget_dupe": "Arket or COS for the architectural basics. One strong vintage piece from the neighbourhood itself — the LES still has thrift stores that will provide."}}',
true),

-- 10. Top of The Standard / Boom Boom Room
('11111111-0000-0000-0000-000000000001',
'Top of The Standard',
'Meatpacking District',
'Rooftop Bar',
'The 18th floor of The Standard High Line, perched over the Hudson on stilts above the old meatpacking district. The views cover the river, Jersey City, and the entire western edge of Manhattan. The Le Bain club and the Boom Boom Room below it are the closest thing New York has to a proper nightlife institution — which means the door policy is real, the crowd is deliberate, and the drinks are worth the price if only because the view makes everything taste better.',
40.7396000, -74.0075000,
NULL,
4,
'{"men": {"brands": ["Saint Laurent", "Acne Studios", "Audemars Piguet", "Corthay"], "outfit": {"top": "Black slim blazer or a dark Saint Laurent shirt — the door policy here responds to intentional dressing", "bottom": "Dark slim jeans or black tailored trousers", "shoes": "Clean black Chelsea boots or a dark leather Oxford", "bag": "Nothing", "accessories": "A watch that doesn''t shout — AP Royal Oak reads correctly here; a Submariner also works"}, "color_palette": "Black, deep navy, dark grey — this is an evening location and the sunset over the Hudson is the only color you need", "budget_dupe": "A well-fitted black blazer from H&M or ASOS, dark jeans, clean black boots. The key word for this door is intentional. Look like you chose every piece."}, "women": {"brands": ["Saint Laurent", "Jacquemus", "Versace", "Louboutin"], "outfit": {"top": "A slip dress in black or deep navy, or a structured crop top and tailored trousers", "bottom": "High-waisted cigarette trousers or a short fluid skirt", "shoes": "Strappy heeled sandal or pointed-toe heel — the roof terrace is a concrete deck, heels are manageable", "bag": "A small crossbody or clutch — you''ll be standing most of the time", "accessories": "Statement earrings, a thin gold or silver body chain, keep the neck clean"}, "color_palette": "Black, deep cobalt, sheer — this crowd dresses for the city, not the neighborhood", "budget_dupe": "A great vintage slip dress and quality heels. The view from the roof does enormous work on behalf of every outfit up here."}}',
true),

-- 11. Summit One Vanderbilt
('11111111-0000-0000-0000-000000000001',
'Summit One Vanderbilt',
'Midtown',
'Art World',
'The observation experience on the upper floors of One Vanderbilt is an art installation before it is a view. Kenzo Digital''s Summit experience is all mirrors and mist and glass elevators extending over 42nd Street. The views are, by any objective measure, the best in Manhattan — but the thing that sets it apart is the deliberate blurring of the line between standing inside a skyscraper and standing in the clouds.',
40.7527000, -73.9777000,
NULL,
2,
'{"men": {"brands": ["Any well-assembled outfit", "Good sneakers are appropriate", "Casual fine"], "outfit": {"top": "Relaxed but considered — a good crewneck or a structured shirt in a clean colour", "bottom": "Dark jeans or straight-leg chinos", "shoes": "Clean white or neutral sneakers — you''ll be walking on glass floors", "bag": "Small backpack or crossbody — you need your hands free for photos", "accessories": "Minimal — the mirrored rooms will multiply everything you wear"}, "color_palette": "Solids only — patterns fragment strangely in the mirror rooms. Navy, black, white, grey.", "budget_dupe": "This is a tourist experience with a luxury price point. A clean, solid-colour outfit from anywhere is appropriate. The installation is the show."}, "women": {"brands": ["Any", "The mirrors will make you look great regardless"], "outfit": {"top": "A solid-colour top or dress — the reflection rooms are built for photos and patterns distort", "bottom": "High-waisted trousers or a fitted midi skirt in a single colour", "shoes": "Comfortable but clean — there is a lot of walking and some glass floors", "bag": "Small — crossbody or clutch, you want both hands", "accessories": "Minimal jewellery that won''t cause an infinity problem in the mirrors"}, "color_palette": "Monochromatic — pick one colour and commit. The mirror rooms will do the rest.", "budget_dupe": "A great outfit from anywhere looks exceptional in the Summit mirrors. The architecture is democratically photogenic."}}',
true),

-- 12. Edge at Hudson Yards
('11111111-0000-0000-0000-000000000001',
'Edge at Hudson Yards',
'Hudson Yards',
'Art World',
'The highest outdoor sky deck in the Western Hemisphere, which is a fact that stops feeling abstract when you are standing on a glass-floored triangle projecting 100 stories over the Hudson River. The views take in the entirety of lower and midtown Manhattan, the Hudson, and on clear days, New Jersey in a way that almost makes New Jersey look acceptable. The champagne bar up here is a reasonable idea that the altitude makes feel inevitable.',
40.7537000, -74.0023000,
NULL,
2,
'{"men": {"brands": ["Practical and photogenic"], "outfit": {"top": "Clean solid-colour sweatshirt or structured shirt — wind is a factor at 100 floors", "bottom": "Dark jeans or trousers — it can be cold even in summer", "shoes": "Clean sneakers or loafers with grip", "bag": "Small backpack or nothing", "accessories": "Sunglasses — essential — and a watch that photographs well against the skyline"}, "color_palette": "Navy, black, slate — colours that work against sky. Avoid white in direct sun at this altitude.", "budget_dupe": "Any clean, fitted outfit in a solid colour. The Hudson Yards architecture has strong opinions and your outfit is a footnote."}, "women": {"brands": ["Practical chic"], "outfit": {"top": "A fitted turtleneck or structured jacket — the deck is exposed and the wind is real", "bottom": "Tailored trousers or straight-leg jeans", "shoes": "Sneakers or block-heel boots with grip — glass floor, some movement", "bag": "Crossbody with a zip — the wind has opinions about open bags at this altitude", "accessories": "Secure earrings, no scarves unless tied tightly, sunglasses are essential"}, "color_palette": "Jewel tones work beautifully at altitude — cobalt, emerald, deep burgundy against the sky and river", "budget_dupe": "The observation deck itself is the experience. Dress for wind and glass floors and you''ve made the correct choice."}}',
true),

-- 13. The Oculus
('11111111-0000-0000-0000-000000000001',
'The Oculus',
'Financial District',
'Continental',
'Santiago Calatrava''s $3.9 billion transit hub is the most polarising piece of architecture in New York, which is saying something. Whether you think it looks like a bird or a stegosaurus, you cannot deny that the interior — a great white rib-vaulted hall of marble and glass — is one of the most extraordinary public spaces in the city. Walk through it at 9am when the morning light falls through the spine and you will briefly understand why architecture matters.',
40.7117000, -74.0130000,
NULL,
1,
'{"men": {"brands": ["Whatever you''re wearing downtown", "This is a transit hub"], "outfit": {"top": "A clean, considered outfit — the Oculus rewards people who look like they belong in a white marble hall", "bottom": "Dark trousers or jeans", "shoes": "Clean shoes — the floors are white marble and reflective", "bag": "A work bag or structured tote — you look like you''re on your way somewhere important", "accessories": "A watch, nothing else necessary"}, "color_palette": "The Oculus is white and light — dark colours create a striking contrast, all-cream reads as architectural", "budget_dupe": "This is public infrastructure. The architecture is free. Wear whatever makes you feel like you belong in a white marble cathedral."}, "women": {"brands": ["Whatever reads as intentional"], "outfit": {"top": "Something structured — the soaring white space rewards a jacket or coat", "bottom": "Tailored trousers or a clean midi skirt", "shoes": "Clean leather shoes — the white marble floor is unforgiving on scuffed heels", "bag": "A structured bag worn seriously, as if you have somewhere to be", "accessories": "Minimal — the space is the statement"}, "color_palette": "All-black is the natural foil to the white interior. All-cream disappears into the building in the best possible way.", "budget_dupe": "Any clean, well-assembled outfit. The Oculus is the most democratic luxury space in New York — the architecture is free and the light is extraordinary."}}',
true),

-- 14. Grand Central Terminal
('11111111-0000-0000-0000-000000000001',
'Grand Central Terminal',
'Midtown',
'Continental',
'The greatest room in New York, by area and by argument. The main concourse — with its turquoise-and-gold celestial ceiling, its marble floors, its forty-foot windows — was almost demolished in the 1960s and saved by a preservation movement that Jackie Kennedy helped lead. The Oyster Bar downstairs is a New York institution. The Campbell Bar upstairs is a hidden room in a 1920s financier''s private office. Walk through the main hall when a shaft of light comes through those south windows and remember that cities still occasionally build extraordinary things.',
40.7527000, -73.9771000,
NULL,
2,
'{"men": {"brands": ["Appropriately serious"], "outfit": {"top": "A blazer or good coat — Grand Central rewards looking like you arrived on a train from somewhere worth coming from", "bottom": "Tailored trousers or dark jeans", "shoes": "Leather shoes — the marble floor is the stage", "bag": "A proper bag with some weight to it — briefcase, structured tote", "accessories": "A watch. This is a place that takes time seriously."}, "color_palette": "Navy, charcoal, camel — the palette of American institutional authority at its best", "budget_dupe": "A clean blazer from anywhere, leather-soled shoes. Grand Central is public infrastructure that happens to be sublime. Dress like you appreciate that."}, "women": {"brands": ["Composed and purposeful"], "outfit": {"top": "A structured coat or blazer — the scale of the main concourse makes casual dress look small", "bottom": "Tailored trousers or a midi skirt with movement", "shoes": "Heels or pointed-toe flats in leather — you are walking on 1913 marble", "bag": "A serious bag — structured leather tote or a proper handbag", "accessories": "Simple gold or silver, nothing that makes noise. The building has its own acoustics."}, "color_palette": "Dark emerald, deep navy, cream and gold — the building''s palette is celestial and yours should respond to it", "budget_dupe": "A great coat from anywhere. Grand Central is the most beautiful commuter terminal ever built and everyone who passes through it is briefly part of something magnificent."}}',
true),

-- 15. NYPL Rose Main Reading Room
('11111111-0000-0000-0000-000000000001',
'NYPL Rose Main Reading Room',
'Midtown',
'Intellectual',
'The Rose Main Reading Room on the third floor of the Stephen A. Schwarzman Building is 297 feet long and absolutely silent. It has been in continuous use since 1911, except for a restoration period. The ceiling murals depict clouds. The oak tables are original. The researchers at the long tables are working on real things. You are allowed to sit here and read whatever you like, provided you are quiet and treat the room with the seriousness it deserves.',
40.7531000, -73.9822000,
NULL,
3,
'{"men": {"brands": ["A.P.C.", "Uniqlo", "Acne Studios"], "outfit": {"top": "A considered top — a good Oxford shirt or a fine crewneck in grey or navy", "bottom": "Straight-leg dark trousers or well-kept jeans", "shoes": "Quiet leather soles — the reading room has a sound culture that deserves respect", "bag": "A serious tote or leather satchel with a book or two in it (required)", "accessories": "A watch — analog, obviously. A fountain pen if you are comfortable with the commitment."}, "color_palette": "Camel, navy, grey, ivory — the palette of someone who reads for pleasure and takes notes in margins", "budget_dupe": "The reading room is free. Bring a book, dress neatly, behave well. The architecture will do the rest."}, "women": {"brands": ["Vince", "Theory", "Toast"], "outfit": {"top": "A fine knit or tailored blouse in cream, camel, or deep navy", "bottom": "Straight-leg trousers or a midi skirt in a muted tone", "shoes": "Flat leather shoes — rubber soles ideally, for silence on the marble floors", "bag": "A canvas tote with books in it — this is not the right venue for an evening bag", "accessories": "Reading glasses if you have them. A simple watch. Nothing that rattles."}, "color_palette": "Camel, cream, dusky rose, grey — the palette of someone who considers the library a form of sanctuary", "budget_dupe": "The Rose Reading Room is one of the most beautiful rooms in New York and entirely free. Dress like you respect the institution."}}',
true),

-- 16. The Metropolitan Museum of Art
('11111111-0000-0000-0000-000000000001',
'The Metropolitan Museum of Art',
'Upper East Side',
'Art World',
'The largest art museum in the Western Hemisphere and possibly the greatest argument for New York''s continued relevance. The Egyptian Temple of Dendur, the arms and armour, the rooftop sculpture garden in summer, and an Impressionist collection that would embarrass any European city — all free with a voluntary donation that most people interpret loosely. The steps outside are both a social scene and a legitimate place to eat a hotdog in an expensive coat.',
40.7794000, -73.9632000,
NULL,
2,
'{"men": {"brands": ["Anything well-assembled", "The Met Steps require a certain quality of nonchalance"], "outfit": {"top": "A structured blazer or a quality turtleneck — the museum''s interiors reward looking like you visit regularly", "bottom": "Dark jeans or tailored trousers", "shoes": "Comfortable leather shoes or clean sneakers — significant walking", "bag": "A canvas museum bag or leather tote", "accessories": "A watch that speaks to cultural affiliation rather than financial status"}, "color_palette": "Navy, charcoal, camel — classic Upper East Side intellectual, as opposed to Upper East Side financial", "budget_dupe": "The Met steps and the Impressionist galleries are available to anyone. A blazer from a good thrift store on Madison Avenue, actually."}, "women": {"brands": ["Whatever makes you look like you belong in a Vermeer"], "outfit": {"top": "A structured blazer or art-world turtleneck in black or camel", "bottom": "Straight-leg trousers or a tailored midi skirt", "shoes": "Comfortable flats or low boots — four hours on marble floors is a commitment", "bag": "A serious tote or a canvas museum bag — both are acceptable", "accessories": "Architectural earrings or a good brooch — the Met is the right venue for interesting jewelry"}, "color_palette": "Black, camel, deep blue, forest green — whatever you would wear to a vernissage in a city that takes art seriously", "budget_dupe": "The Met''s suggested admission is voluntary. A great outfit from anywhere. The context is the luxury."}}',
true),

-- 17. The Guggenheim Museum
('11111111-0000-0000-0000-000000000001',
'The Guggenheim Museum',
'Upper East Side',
'Art World',
'Frank Lloyd Wright''s inverted ziggurat on Fifth Avenue is the building that most reliably makes first-time visitors to New York recalibrate their expectations. The interior rotunda — a continuous spiral of concrete ramps around a central skylit void — is more photogenic than most of the art it contains, and the art is extraordinary. The Saturday evening crowd during opening weeks of major exhibitions is as competitive as any gallery in the world.',
40.7830000, -73.9591000,
NULL,
3,
'{"men": {"brands": ["Acne Studios", "Lemaire", "Our Legacy", "COS"], "outfit": {"top": "A considered minimal piece — the Guggenheim is a temple to modernism and respects people who understand that", "bottom": "Well-cut dark trousers or slim dark jeans", "shoes": "Clean minimalist shoes — the rotunda echoes", "bag": "A slim leather bag or nothing", "accessories": "A design-forward watch — Nomos, Junghans, or Braun if you can find one"}, "color_palette": "Black, white, grey, warm concrete — the building''s palette is your guide", "budget_dupe": "COS or Arket for clean modernist separates. The Guggenheim crowd skews art world, which means considered dressing at various price points is completely normal."}, "women": {"brands": ["Celine", "Issey Miyake", "Jil Sander", "Toteme"], "outfit": {"top": "An architectural piece — a Miyake pleated top, a strong blazer in a clean line, or a minimal dress in black or white", "bottom": "Wide-leg trousers in grey or cream, or a structured A-line skirt", "shoes": "Minimal leather flats or a low block heel — the ramp is better navigated in flats", "bag": "A sculptural bag or a very clean structured piece", "accessories": "One strong piece of interesting jewelry rather than several ordinary ones"}, "color_palette": "White, black, concrete grey — respond to the architecture, let the art provide the colour", "budget_dupe": "One architectural vintage piece from a good consignment shop, COS basics for the rest. The Guggenheim community rewards genuine aesthetic thought over fashion labels."}}',
true),

-- 18. Tiffany & Co. Flagship
('11111111-0000-0000-0000-000000000001',
'Tiffany & Co. Flagship',
'Midtown',
'Luxury Retail',
'The building at the corner of Fifth and 57th has been the global headquarters of a particular kind of American aspiration since 1940. The renovation under LVMH returned it to something close to the platonic idea of Tiffany Blue. The fourth floor café — a real working restaurant — is named after Breakfast at Tiffany''s and serves eggs Benedict to people who have come specifically to say they did. Browse slowly, touch nothing that you haven''t been invited to touch, and understand that you are visiting a kind of secular temple.',
40.7626000, -73.9740000,
NULL,
3,
'{"men": {"brands": ["Brunello Cucinelli", "Canali", "Tiffany & Co. (obviously)", "Berluti"], "outfit": {"top": "A fitted sport coat in grey or navy, or a very well-cut blazer — this is Fifth and 57th", "bottom": "Dark trousers, perfectly pressed", "shoes": "Leather Oxfords or loafers in black or tan, polished", "bag": "Nothing, or a very slim portfolio", "accessories": "One good watch, understated. If you''re buying jewelry, the case will handle the styling."}, "color_palette": "Navy, charcoal, cream — the palette of someone for whom Tiffany Blue is a reference point, not a surprise", "budget_dupe": "A clean sport coat from anywhere well-pressed. You are being watched by people who sell jewelry for a living. Aim for composed."}, "women": {"brands": ["The Row", "Max Mara", "Tiffany & Co. (the point)", "Gianvito Rossi"], "outfit": {"top": "A classic camel coat over a black turtleneck, or an ivory blazer over a silk blouse", "bottom": "Tailored trousers in black or cream", "shoes": "Clean pointed-toe heels or flats in black or nude", "bag": "A structured classic bag — dark leather, no excessive branding", "accessories": "Whatever Tiffany you already own. If none: small gold studs. You are here to look at things that will improve your accessory situation."}, "color_palette": "Black, cream, camel — classic New York shopping day on Fifth Avenue", "budget_dupe": "A great camel coat (H&M or Zara have had good versions) over an all-black outfit. You''re here to look and possibly to eat eggs Benedict on the fourth floor."}}',
true),

-- 19. Lincoln Center
('11111111-0000-0000-0000-000000000001',
'Lincoln Center for the Performing Arts',
'Upper West Side',
'Art World',
'The plaza at Lincoln Center — the Metropolitan Opera, the New York Philharmonic, the New York City Ballet, all arranged around a central fountain — is one of the great civic spaces in America. Evening performances draw a crowd that still dresses for the occasion, which is increasingly rare and therefore worth participating in. Even if you''re not going inside, the plaza on a summer evening, with the fountain lit and the pre-concert crowd in good suits, is one of the more civilised things the city offers.',
40.7725000, -73.9834000,
NULL,
3,
'{"men": {"brands": ["Canali", "Zegna", "Rolex", "Church''s"], "outfit": {"top": "A dark suit — navy or charcoal — or a dinner jacket if the occasion warrants. Lincoln Center is one of the last places in New York where black tie still appears organically.", "bottom": "Matching trousers, a clean break", "shoes": "Black cap-toes for suit, black patent for black tie", "bag": "Nothing or slim leather portfolio for pre-performance drinks", "accessories": "Rolex or Cartier, silk pocket square, optional tie depending on the occasion"}, "color_palette": "Navy, charcoal, black — the classic evening palette that has not changed because it does not need to", "budget_dupe": "SuitSupply Napoli in navy. One good tie from a department store. The Lincoln Center plaza makes a well-fitted mid-priced suit look like the right answer."}, "women": {"brands": ["Carolina Herrera", "Oscar de la Renta", "Valentino", "Manolo Blahnik"], "outfit": {"top": "An evening dress in a deep colour — emerald, midnight blue, or black — or a structured blazer over wide-leg silk trousers for a less formal evening", "bottom": "An A-line or floor-length skirt if attending the opera; tailored trousers for the ballet or philharmonic", "shoes": "A proper heel — the plaza cobblestones are navigable in block heels", "bag": "An evening clutch or small structured bag", "accessories": "Statement earrings, a good necklace, possibly opera gloves if the occasion is right and you are prepared to commit"}, "color_palette": "Deep emerald, midnight blue, black, champagne — evening colours that the plaza fountain will reflect beautifully", "budget_dupe": "A vintage evening gown from a consignment shop is both cheaper and more interesting than most RTW evening wear. Lincoln Center is one of the few remaining venues where dressing well is a form of civic participation."}}',
true),

-- 20. Bryant Park
('11111111-0000-0000-0000-000000000001',
'Bryant Park',
'Midtown',
'Weekend Aristocrat',
'The park behind the New York Public Library, surrounded on three sides by Midtown skyscrapers, is one of the best-managed public spaces in America. The café under the trees, the movable chairs, the winter rink and summer lawn films — it achieves the quality of a private park without being one. The Fashion Week shows were here for twenty years. In summer, the lawn is a class-mixing space where someone on a phone call about a hedge fund sits next to someone eating a sandwich from a nearby deli, and both are equally correct.',
40.7536000, -73.9832000,
NULL,
2,
'{"men": {"brands": ["Whatever you own that sits between work and weekend"], "outfit": {"top": "A relaxed sport coat or a quality crewneck — the Bryant Park café rewards looking slightly above casual", "bottom": "Chinos in stone or navy, or dark jeans with a clean hem", "shoes": "Leather loafers or clean white sneakers", "bag": "A canvas tote or slim leather bag", "accessories": "Sunglasses, a watch — nothing elaborate"}, "color_palette": "Stone, navy, cream, olive — midday in a Midtown park that takes itself seriously", "budget_dupe": "Any clean, considered outfit works here. Bryant Park is a democratic luxury. The Midtown office workers on lunch are at every price point and all of them belong."}, "women": {"brands": ["Anything that reads as effortlessly put-together"], "outfit": {"top": "A blazer over a ribbed tank, or a silk blouse under a quality trench coat", "bottom": "Tailored wide-leg trousers or a midi skirt in a seasonal colour", "shoes": "Loafers or block-heel mules — the park''s gravel and grass paths reward stable footwear", "bag": "A quality tote or structured shoulder bag", "accessories": "A good pair of sunglasses is mandatory. The park is fully exposed."}, "color_palette": "Sage, stone, cream, dusty rose — the seasonal colours of a well-curated Midtown afternoon", "budget_dupe": "This is a public park. A well-assembled outfit from anywhere. The movable chairs, the fountain, the view of the library — the luxury is entirely free."}}',
true),

-- 21. Bethesda Terrace
('11111111-0000-0000-0000-000000000001',
'Bethesda Terrace, Central Park',
'Upper West Side',
'Weekend Aristocrat',
'The formal terrace at the 72nd Street transverse, centred on the Angel of the Waters fountain, is the architectural heart of Central Park. The lower terrace arcade has Victorian tilework that was recently restored to its 1873 condition. The rowboat lake spreads south of it. On weekends, the terrace is simultaneously a tourist attraction, a wedding photography location, a skateboarder''s venue, a jazz performance space, and a place where entirely unbothered New Yorkers sit and read. It contains multitudes and manages all of them.',
40.7738000, -73.9701000,
NULL,
1,
'{"men": {"brands": ["Weekend ease is the standard here"], "outfit": {"top": "A relaxed overshirt or quality t-shirt — Central Park is informal but a well-chosen casual piece reads well against the Victorian architecture", "bottom": "Dark jeans or chinos", "shoes": "Clean white sneakers or leather-soled loafers", "bag": "Nothing or a canvas tote", "accessories": "Sunglasses — essential. A watch if it''s your habit."}, "color_palette": "Navy, stone, olive, cream — outdoor leisure at the greatest urban park in the world", "budget_dupe": "Whatever you wear well, worn well. The park provides all the context you need."}, "women": {"brands": ["Casual and considered"], "outfit": {"top": "A linen shirt or quality blouse in a seasonal colour, or a relaxed sundress", "bottom": "Wide-leg linen trousers or a breezy midi skirt", "shoes": "Comfortable flats or clean sneakers — this is a walking venue", "bag": "A canvas tote or crossbody — Central Park is a pickpocket environment and an active one", "accessories": "Sunglasses, a simple necklace, practical earrings"}, "color_palette": "Seasonal florals, sage, cream, terracotta — whatever works against the park''s greenery and Victorian stonework", "budget_dupe": "A linen shirt from Uniqlo and well-worn jeans. Central Park is the great equaliser of New York real estate."}}',
true),

-- 22. Conservatory Garden
('11111111-0000-0000-0000-000000000001',
'Conservatory Garden',
'Upper East Side',
'Weekend Aristocrat',
'The only formal garden in Central Park, at the northeastern corner near 105th Street. Six acres of Italian, French, and English formal garden design, free and open daily. The Vanderbilt Gate at the entrance is original Beaux Arts ironwork. The Great Lawn equivalent of the Upper East Side — except here there are wisteria arbours and a central fountain and almost nobody from the tourist circuit who made it this far north. The correct way to experience this garden is slowly, in good shoes, with something to read.',
40.7954000, -73.9520000,
NULL,
2,
'{"men": {"brands": ["Whatever reads as Sunday morning appropriate"], "outfit": {"top": "A fine merino crewneck or a light Oxford shirt — the Conservatory Garden is the kind of place where looking slightly dressed up feels correct", "bottom": "Chinos in stone or camel, or soft linen trousers", "shoes": "Leather loafers or leather-soled brogues — this is a formal garden, formal-ish shoes respond", "bag": "A canvas or leather tote with a book in it", "accessories": "A watch, a pair of sunglasses"}, "color_palette": "Stone, camel, cream, pale blue — the palette of a Sunday morning in a formal garden that happens to be free", "budget_dupe": "Clean chinos and a quality shirt from Uniqlo. The garden is free, the architecture is Vanderbilt, the company is your own."}, "women": {"brands": ["Floral and thoughtful"], "outfit": {"top": "A floral or botanical-print blouse, or a linen dress in a garden-appropriate colour", "bottom": "A midi skirt in a soft print or wide-leg linen trousers in sage or cream", "shoes": "Leather flats or block-heel sandals — the garden paths are gravel and well-maintained", "bag": "A wicker or canvas bag — a botanical garden rewards natural materials", "accessories": "Simple gold or pearl earrings, a linen hat if the season is right"}, "color_palette": "Sage, dusty rose, cream, terracotta — the Conservatory Garden is the most naturally appropriate location in New York for a floral print", "budget_dupe": "A linen dress from Zara or H&M and leather sandals. The garden is one of the most beautiful free spaces in the city and entirely unknown to most visitors."}}',
true),

-- 23. DUMBO / Washington Street
('11111111-0000-0000-0000-000000000001',
'Washington Street, DUMBO',
'DUMBO, Brooklyn',
'Art World',
'The view down Washington Street between the Manhattan and Brooklyn Bridge piers is the most photographed spot in Brooklyn and the second-most-photographed street view in New York after Times Square — except that this one is actually beautiful. The cobblestone street, the cast-iron arches of the bridges converging in the distance, the Empire State Building framed in the gap — it is cinematic in a way that suggests the city was designed specifically for this photograph. The rest of DUMBO has galleries, boutiques, and Grimaldi''s Pizzeria.',
40.7028000, -73.9902000,
NULL,
1,
'{"men": {"brands": ["Brooklyn aesthetic — quality without corporate"], "outfit": {"top": "A heritage workwear piece — a quality canvas jacket, a chambray shirt, a Merz b. Schwanen tee", "bottom": "Dark denim or workwear trousers with a clean leg", "shoes": "Clean leather boots or heritage-style sneakers", "bag": "A canvas tote or nothing", "accessories": "A simple watch, no flash"}, "color_palette": "Indigo, charcoal, cream, rust — DUMBO''s cobblestones and iron bridges are a particular palette", "budget_dupe": "Levi''s, a vintage canvas jacket, leather boots from Thursday Boot Co. This is the most naturally photogenic street in New York and the most accessible."}, "women": {"brands": ["Brooklyn-cool but considered"], "outfit": {"top": "A quality tee or a linen blouse in a warm tone — the cobblestones and the brick buildings reward warm neutrals", "bottom": "High-waisted jeans or a midi skirt in a muted print", "shoes": "Leather boots or clean sneakers — cobblestones in heels is a genuine hazard", "bag": "A small crossbody or a canvas tote", "accessories": "Simple gold rings and earrings, comfortable and practical"}, "color_palette": "Terracotta, warm white, indigo, sage — colours that read beautifully against red brick and cast iron", "budget_dupe": "Levi''s, a quality second-hand jacket, leather ankle boots. The view is free and extraordinary. The photograph will be better than any Instagram vacation you''ve planned."}}',
true),

-- 24. Fanelli's Cafe
('11111111-0000-0000-0000-000000000001',
'Fanelli''s Cafe',
'SoHo',
'Continental',
'Fanelli''s has been a bar and restaurant at Prince and Mercer since 1847, which makes it older than most European institutions that call themselves historic. The pressed tin ceiling, the ancient bar, the framed boxing photographs — none of it is a restoration project. All of it is original. The crowd is mixed between SoHo gallery workers, tourists who found it on a list, and regulars who have been coming since the neighbourhood was manufacturing. Order a beer and a burger. Take nothing from the walls.',
40.7234000, -74.0003000,
NULL,
2,
'{"men": {"brands": ["Whatever you were already wearing"], "outfit": {"top": "A clean t-shirt or a lived-in Oxford shirt — Fanelli''s has a zero-pretension policy that is itself a form of pretension", "bottom": "Dark jeans or chinos", "shoes": "Leather boots or clean sneakers", "bag": "Whatever you came in with", "accessories": "Nothing required"}, "color_palette": "Whatever you own. The pressed tin ceiling has been absorbing every colour palette since before your grandparents were born.", "budget_dupe": "Fanelli''s is the most democratic bar in SoHo. The beer is reasonably priced. The burger is correct. The history is free."}, "women": {"brands": ["Casual and downtown"], "outfit": {"top": "A vintage band tee or a quality loose blouse in white or stripe", "bottom": "Well-worn jeans or a simple midi skirt", "shoes": "Leather ankle boots or clean white sneakers", "bag": "Small crossbody or a canvas tote", "accessories": "Minimal — Fanelli''s is a place for rings accumulated over years, not a coordinated accessories situation"}, "color_palette": "Denim, white, black — the permanent downtown palette that this bar predates by a century", "budget_dupe": "Your most comfortable downtown outfit. The pretension here is in having no pretension at all."}}',
true),

-- 25. Altro Paradiso
('11111111-0000-0000-0000-000000000001',
'Altro Paradiso',
'SoHo',
'Continental',
'Ignacio Mattos''s grown-up Italian restaurant on Spring Street is one of the best restaurants in New York without being one of the loudest about it. The space — warm wood, low lighting, carefully spaced tables — is designed for conversation at normal volumes, which has become a luxury. The pasta is exceptional. The wine list leans natural and Italian. The crowd is creative industry, media, and the serious food people who always know the right place before anyone else does.',
40.7257000, -74.0069000,
NULL,
3,
'{"men": {"brands": ["A.P.C.", "Our Legacy", "Margaret Howell", "Common Projects"], "outfit": {"top": "A quality Oxford shirt in white or chambray, or a fine-knit in grey — Altro Paradiso rewards looking thoughtful rather than dressed-up", "bottom": "Dark slim jeans or tailored chinos", "shoes": "Clean leather loafers or white common projects", "bag": "Nothing or a slim leather wallet", "accessories": "A considered watch, minimal"}, "color_palette": "Navy, cream, camel, stone — the palette of someone who reads restaurant reviews for pleasure", "budget_dupe": "A clean Oxford shirt from anywhere well-fitted, good dark jeans, leather shoes. The crowd here will notice if you''ve thought about it, which is different from how much you spent."}, "women": {"brands": ["Isabel Marant", "Toteme", "Jacquemus", "Vince"], "outfit": {"top": "A silk or linen blouse in ivory or blush, or a quality fine-knit in camel", "bottom": "Wide-leg trousers in cream or oatmeal, or straight-leg dark jeans", "shoes": "Clean leather mule or pointed-toe flat", "bag": "A minimal structured bag or quality leather pouch", "accessories": "Small gold hoops, a thin necklace, minimal rings"}, "color_palette": "Ivory, blush, camel, warm white — food media''s unofficial colour palette", "budget_dupe": "A silk blouse from & Other Stories, good jeans, quality leather sandals. Altro Paradiso''s crowd is warm and intelligent, not intimidating."}}',
true),

-- 26. Piccola Cucina
('11111111-0000-0000-0000-000000000001',
'Piccola Cucina Osteria',
'SoHo',
'Continental',
'A genuinely Sicilian restaurant in SoHo that has resisted becoming a scene for fifteen years. The room is small, the tables are close, the owner is frequently present, and the pasta and fish come with the confidence of someone who doesn''t need to explain where the ingredients are from because they''ve already dealt with that. Reservations are necessary and conversation with the table next to you is inevitable. Neither of these things is a problem.',
40.7261000, -74.0037000,
NULL,
3,
'{"men": {"brands": ["Relaxed Italian sensibility"], "outfit": {"top": "A linen shirt in white or pale blue, untucked with one button undone at the collar — the appropriate uniform for a Sicilian restaurant anywhere in the world", "bottom": "Dark slim trousers or well-cut jeans", "shoes": "Leather loafers in tan or brown", "bag": "Nothing", "accessories": "A simple watch, no other jewelry necessary"}, "color_palette": "White, pale blue, tan — the palette of someone who has actually been to Sicily and eaten well there", "budget_dupe": "A linen shirt from Uniqlo, dark jeans, leather shoes. The food will be the most expensive thing at this table and it will be worth it."}, "women": {"brands": ["Linen and Mediterranean"], "outfit": {"top": "A linen blouse in white or terracotta, or a simple cotton sundress in a warm tone", "bottom": "Wide-leg linen trousers or a midi skirt in a soft earth colour", "shoes": "Flat leather sandals or leather mules", "bag": "A small straw or leather bag", "accessories": "Gold hoops, a simple bracelet, nothing that makes it hard to eat pasta properly"}, "color_palette": "White, terracotta, warm sand, sage — the palette of a Sicilian summer transplanted to a SoHo side street", "budget_dupe": "A linen dress or set from H&M Premium, leather sandals. The ambience here is warm and genuinely Italian, not themed."}}',
true),

-- 27. Estela
('11111111-0000-0000-0000-000000000001',
'Estela',
'NoLIta',
'Power Lunch',
'Ignacio Mattos''s first New York restaurant, above a ground-floor wine bar on East Houston, has been one of the most consistent destinations in the city since it opened in 2013. The food is genuinely adventurous — small plates that reference multiple traditions without belonging to any one of them. President Obama had lunch here in 2016 and did not ruin it. The upstairs dining room is one of the most pleasant rooms to sit in New York: intimate, well-lit, unpretentious.',
40.7226000, -73.9979000,
NULL,
3,
'{"men": {"brands": ["Relaxed and intelligent"], "outfit": {"top": "A fine oxford or a quality t-shirt under a blazer — Estela is food-serious without being dress-code serious", "bottom": "Dark slim jeans or tailored trousers", "shoes": "Clean leather loafers or a quality sneaker", "bag": "Small leather bag or nothing", "accessories": "A considered watch"}, "color_palette": "Navy, charcoal, white, stone — the palette of someone who has an opinion about natural wine", "budget_dupe": "A quality t-shirt and a blazer from anywhere. The food is the priority here. Estela''s crowd is smart and curious, not fashion-focused."}, "women": {"brands": ["Toteme", "Isabel Marant", "COS"], "outfit": {"top": "A silk blouse in white or neutral, or a quality knitwear piece in ivory or slate", "bottom": "Dark straight-leg jeans or wide-leg trousers", "shoes": "Clean leather flats or ankle boots", "bag": "A quality crossbody or minimal structured bag", "accessories": "Simple gold or silver earrings, a thin necklace"}, "color_palette": "Ivory, stone, slate, white — sophisticated without being dressed up, which is the hardest register to achieve", "budget_dupe": "A silk blouse from & Other Stories and good jeans. Estela is about the food and the conversation. The room will do the rest."}}',
true),

-- 28. Pastis
('11111111-0000-0000-0000-000000000001',
'Pastis',
'Meatpacking District',
'Continental',
'Keith McNally''s French brasserie originally opened in 1999 and defined the Meatpacking District for a decade before the neighbourhood became what it is now. The reproduction closed in 2014 and reopened in 2019 in a new location on Gansevoort, rebuilt with the same tin ceilings, zinc bar, and deliberately scuffed mirrors as if no time had passed. The weekend brunch line is a social occasion in itself. The steak frites remain non-negotiable.',
40.7398000, -74.0065000,
NULL,
3,
'{"men": {"brands": ["Saint Laurent", "A.P.C.", "Acne Studios"], "outfit": {"top": "A worn-in but quality piece — a vintage leather jacket, a good chambray shirt, a slim blazer in charcoal or navy", "bottom": "Dark slim jeans or straight-leg trousers", "shoes": "Chelsea boots or clean leather sneakers", "bag": "Nothing or a very small crossbody", "accessories": "A simple watch, nothing more"}, "color_palette": "Black, dark denim, charcoal, slate — the Meatpacking District''s permanent evening palette", "budget_dupe": "Levi''s, a vintage jacket, Chelsea boots from Thursday Boot Co. Pastis has the energy of a place that was briefly the most important restaurant in New York and still remembers what that felt like."}, "women": {"brands": ["Isabel Marant", "Ganni", "Toteme"], "outfit": {"top": "A French-inflected piece — a Breton stripe, a wrap blouse in silk, a good blazer over a simple top", "bottom": "Straight-leg jeans or a bias-cut midi skirt", "shoes": "Ankle boots or a clean ballet flat", "bag": "A quality leather crossbody", "accessories": "Gold hoops, a simple necklace, the French approach to accessories applies here"}, "color_palette": "Navy, white, red, charcoal — the brasserie palette that Pastis practically invented for New York", "budget_dupe": "A Breton stripe top from Petit Bateau or Saint James, good jeans, leather ankle boots. Pastis''s charm is that it has been aspirational at every price point since 1999."}}',
true),

-- 29. Le Coucou
('11111111-0000-0000-0000-000000000001',
'Le Coucou',
'NoLIta',
'Continental',
'Daniel Rose''s French restaurant in the 11 Howard hotel lobby is the best French restaurant in New York and possibly the most beautiful restaurant room in the city. The space — a gilded, high-ceilinged, chandelier-hung room of cream and gold — operates as both a genuine grand restaurant and a deliberate performance of what a grand French restaurant is. The food matches the room. Reservations are hard. The effort is worth it.',
40.7218000, -73.9970000,
NULL,
5,
'{"men": {"brands": ["Brioni", "Kiton", "Tom Ford", "John Lobb"], "outfit": {"top": "A dark suit or a blazer of serious quality — Le Coucou has a dress code in spirit if not in letter, and the room will make you feel underdressed if you arrive in jeans", "bottom": "Matching or coordinated trousers, pressed", "shoes": "Leather Oxfords or polished loafers in black or dark brown", "bag": "Nothing", "accessories": "A good watch, a pocket square in white linen, nothing else"}, "color_palette": "Navy, charcoal, black, ivory — a room this beautiful requires you to be equally composed", "budget_dupe": "SuitSupply Napoli in dark navy. This is a special-occasion restaurant — the investment in a well-fitted suit is amortised over many dinners."}, "women": {"brands": ["Valentino", "Oscar de la Renta", "Cartier", "Aquazzura"], "outfit": {"top": "A dress — this is a dress restaurant. Silk, structured, in a colour that can hold its own in a gilded room. Deep green, champagne, midnight blue.", "bottom": "An A-line or fitted silhouette, midi to floor length for dinner", "shoes": "A proper heel — the room is formal and the floor is stone", "bag": "An evening clutch or small structured bag", "accessories": "Statement earrings, a thin necklace, full jewelry for a special occasion"}, "color_palette": "Deep emerald, champagne, midnight blue, ivory — the room is gilded and your palette should respond with something equally serious", "budget_dupe": "A great vintage evening dress from a consignment shop. Le Coucou is one of the only restaurants in New York where this investment in dressing makes the meal significantly better."}}',
true),

-- 30. Via Carota
('11111111-0000-0000-0000-000000000001',
'Via Carota',
'West Village',
'Continental',
'Jody Williams and Rita Sodi''s Italian trattoria on Grove Street has become one of the most loved restaurants in New York for the most durable reason: it is genuinely excellent and has never become its own parody. The insalata verde is the reason people wait two hours for a table without a reservation. The room is warm, crowded, and lit for maximum flattery. The West Village regulars who line up outside are the people who live in the most desirable neighbourhood in the city and know it.',
40.7333000, -74.0037000,
NULL,
3,
'{"men": {"brands": ["A.P.C.", "Our Legacy", "Vince"], "outfit": {"top": "A quality Oxford or linen shirt in white, or a fine merino crewneck in camel or grey", "bottom": "Slim dark jeans or chinos in stone or navy", "shoes": "Clean leather loafers in tan or cognac — West Village Italian dinner calls for leather on your feet", "bag": "Nothing", "accessories": "A simple watch, a ring if it''s your habit"}, "color_palette": "Cream, navy, stone, camel — the West Village''s preferred Saturday evening palette", "budget_dupe": "A quality Oxford shirt, good dark jeans, leather loafers. The crowd at Via Carota is warm and well-dressed in the way that means they didn''t try very hard."}, "women": {"brands": ["Isabel Marant", "Toteme", "Vince", "Jenni Kayne"], "outfit": {"top": "A silk blouse in ivory or warm white, or a quality knit in camel or terracotta", "bottom": "High-waisted straight-leg jeans or wide-leg linen trousers", "shoes": "Leather loafers or simple block-heel mules", "bag": "A quality leather bag that has been used enough to look lived-in", "accessories": "Gold hoops, stacked rings, a thin necklace — the warm accessories energy of the West Village"}, "color_palette": "Ivory, camel, terracotta, warm white — the Via Carota crowd looks like they arrived straight from a very good apartment nearby", "budget_dupe": "A silk blouse from & Other Stories, Levi''s, good leather loafers. The restaurant is about warmth and quality. Your outfit should suggest the same."}}',
true),

-- 31. Bar Pitti
('11111111-0000-0000-0000-000000000001',
'Bar Pitti',
'West Village',
'Continental',
'Bar Pitti on Sixth Avenue has been a scene since before the West Village became what it is now. The outdoor tables in summer are a casting call for downtown New York''s best-looking and most interesting people. The Florentine food is simple and correct. The waiters are politely dismissive in a way that is itself part of the experience. There is no reservation system. This is a statement of confidence, not an oversight.',
40.7336000, -74.0019000,
NULL,
4,
'{"men": {"brands": ["Saint Laurent", "A.P.C.", "Acne Studios", "Our Legacy"], "outfit": {"top": "A quality white tee or a fine short-sleeve button-down — outdoor Bar Pitti in summer is a fashion event without being a fashion event", "bottom": "Dark slim jeans or well-cut chinos in a warm tone", "shoes": "Clean leather sneakers or loafers — the outdoor tables are cobblestone-adjacent", "bag": "Nothing or a minimal crossbody", "accessories": "Sunglasses are essential. A simple watch. A ring if it''s your personal brand."}, "color_palette": "White, black, dark denim — the eternal downtown Italian-American casual palette", "budget_dupe": "A perfect white tee from James Perse or COS, great jeans, clean leather shoes. Bar Pitti rewards the quality of your nonchalance more than any other single factor."}, "women": {"brands": ["Isabel Marant", "Ganni", "Jacquemus", "Toteme"], "outfit": {"top": "A simple slip dress in ivory or black, or a quality linen blouse with good jeans", "bottom": "High-waisted straight-leg jeans or a flowing midi skirt", "shoes": "Leather sandals or clean loafers for the outdoor tables", "bag": "A small quality leather bag worn crossbody", "accessories": "Gold hoops, a thin necklace, sunglasses — the outdoor table at Bar Pitti in summer is the closest New York gets to a Florentine piazza"}, "color_palette": "White, ivory, black, warm denim — the colours of someone who lives nearby and stops here four times a week", "budget_dupe": "A great linen shirt and quality jeans. Bar Pitti''s outdoor tables have an unspoken social assessment that responds to overall quality of presence rather than specific labels."}}',
true),

-- 32. Sant Ambroeus West Village
('11111111-0000-0000-0000-000000000001',
'Sant Ambroeus West Village',
'West Village',
'Continental',
'The West Village outpost of the Milanese institution has its own identity distinct from the Upper East Side location — the light is different, the neighbourhood is younger, and the espresso bar in front fills up with a more creative industry crowd. The back dining room is darker and more intimate. The pastries are as good as the Upper East Side. In summer, a table outside on West 4th Street is one of the most civilised places in Manhattan.',
40.7347000, -74.0043000,
NULL,
3,
'{"men": {"brands": ["A.P.C.", "Vince", "Acne Studios"], "outfit": {"top": "A relaxed but quality piece — a French-tuck oxford, a fine turtleneck in grey or camel, a soft blazer", "bottom": "Dark slim jeans or tailored chinos", "shoes": "Clean leather loafers or minimal white sneakers", "bag": "Nothing or a very slim leather wallet", "accessories": "A simple watch, possibly sunglasses"}, "color_palette": "Cream, camel, navy, charcoal — the West Village Sant Ambroeus crowd is slightly more relaxed than the UES version", "budget_dupe": "Quality basics from COS or Uniqlo. The coffee is the priority. Dress like you live nearby and can afford to take the morning slowly."}, "women": {"brands": ["Toteme", "Isabel Marant", "Vince", "Jenni Kayne"], "outfit": {"top": "A silk blouse in cream or warm ivory, or a quality knit cardigan over a simple top", "bottom": "Straight-leg dark jeans or wide-leg cream trousers", "shoes": "Leather loafers or pointed-toe flats", "bag": "A quality tote or structured shoulder bag that you''ve been using for three years and it shows", "accessories": "Small gold hoops, a simple ring, nothing elaborate for coffee"}, "color_palette": "Ivory, warm cream, camel, soft blush — the palette of a West Village morning that began with good espresso", "budget_dupe": "A quality silk blouse from & Other Stories, good jeans, leather shoes. Sant Ambroeus rewards the quality of your morning routine."}}',
true),

-- 33. Carbone
('11111111-0000-0000-0000-000000000001',
'Carbone',
'Greenwich Village',
'Power Lunch',
'The most theatrical Italian-American restaurant in New York, which is a city with strong competition in that category. Mario Carbone and Rich Torrisi''s recreation of a 1950s Manhattan Italian red-sauce joint operates at a level of studied perfection that requires either enormous respect or intense suspicion — possibly both simultaneously. The veal Marsala is the point. The music is correct. The prices are a statement about what something can be worth when it is done with absolute commitment.',
40.7254000, -74.0005000,
NULL,
5,
'{"men": {"brands": ["Tom Ford", "Zegna", "Rolex", "Berluti"], "outfit": {"top": "A dark suit — navy or charcoal — or at minimum a very well-fitted blazer over a dress shirt. Carbone has an implicit dress code enforced by the room''s own authority.", "bottom": "Tailored trousers, pressed", "shoes": "Black or dark brown leather Oxfords or monk straps", "bag": "Nothing", "accessories": "A serious watch — Rolex or similar. A pocket square in white. Carbone is a statement restaurant and your outfit participates in making that statement."}, "color_palette": "Midnight navy, charcoal, black — the palette of a man who understands that this restaurant rewards commitment", "budget_dupe": "SuitSupply in dark navy, one good tie if the table warrants it. The music, the lighting, and the veal Marsala will elevate any well-fitted suit to the occasion."}, "women": {"brands": ["Versace", "Saint Laurent", "Dolce & Gabbana", "Louboutin"], "outfit": {"top": "A dress — and this is a restaurant that supports a properly Italian dress. Something with structure, colour, possibly a pattern. The room is theatrical and rewards a theatrical entrance.", "bottom": "An A-line or column silhouette, knee to midi length", "shoes": "A proper heel — the room is marble and your entrance matters", "bag": "A small structured evening bag or a quality clutch", "accessories": "Statement earrings, a good necklace — Carbone is the right venue for the jewelry you save for special occasions"}, "color_palette": "Deep red, midnight blue, emerald, ivory — colours that read as Italian-American glamour at its best", "budget_dupe": "A great vintage dress from a consignment shop in a dramatic colour. Carbone''s theatre rewards theatricality. The crowd will recognise the effort regardless of the label."}}',
true),

-- 34. Minetta Tavern
('11111111-0000-0000-0000-000000000001',
'Minetta Tavern',
'Greenwich Village',
'Continental',
'Keith McNally''s restoration of the 1937 Greenwich Village institution is a masterclass in the genre: the original Minetta Tavern photographs are on the wall, the black and white tile is period-correct, the Black Label Burger is the best hamburger in New York City, and the room feels like it has been there continuously since Hemingway was drinking in the Village. The crowd is a downtown cross-section. The reservations are difficult. The burger alone justifies both problems.',
40.7307000, -74.0001000,
NULL,
3,
'{"men": {"brands": ["A.P.C.", "Ralph Lauren", "Acne Studios"], "outfit": {"top": "A quality casual piece — a well-worn Oxford shirt, a fine crewneck, a good t-shirt under a blazer", "bottom": "Dark jeans or slim chinos", "shoes": "Clean leather boots or loafers — the Village expects some effort", "bag": "Nothing or a slim crossbody", "accessories": "A simple watch"}, "color_palette": "Navy, charcoal, camel — Greenwich Village''s permanent smart-casual palette", "budget_dupe": "Dark jeans, a quality Oxford shirt, leather boots. Minetta Tavern''s crowd spans price points united by an appreciation for rooms that have actually been somewhere."}, "women": {"brands": ["Toteme", "Vince", "Isabel Marant"], "outfit": {"top": "A silk blouse or quality knit in a warm tone — the room''s photographs and paneling reward warm colours", "bottom": "Dark straight-leg jeans or tailored wide-leg trousers", "shoes": "Leather ankle boots or clean flats", "bag": "A quality everyday bag", "accessories": "Gold hoops, simple ring or bracelet"}, "color_palette": "Camel, ivory, dark denim, warm burgundy — the palette of a Village dinner that might last until midnight", "budget_dupe": "A quality blouse from & Other Stories and good jeans. Minetta''s charm is that it doesn''t require a performance — just appreciation."}}',
true),

-- 35. Raoul's
('11111111-0000-0000-0000-000000000001',
'Raoul''s',
'SoHo',
'Continental',
'Raoul''s on Prince Street opened in 1975 as a French bistro in what was then a manufacturing district. It predates the gallery scene, the boutiques, the cast-iron landmark designation, and the Soho of popular imagination. The steak au poivre is the reason people come. The room — dark, candlelit, hung with the art of regulars — is the reason they stay. This is the kind of restaurant that hasn''t changed because it hasn''t needed to.',
40.7257000, -74.0000000,
NULL,
3,
'{"men": {"brands": ["French nonchalance is the reference"], "outfit": {"top": "A dark blazer or a quality sport coat over an open-collar shirt — Raoul''s is bistro-formal, which is a specific register", "bottom": "Dark slim trousers or smart jeans", "shoes": "Clean leather loafers or low boots", "bag": "Nothing", "accessories": "A simple watch, a pocket square if the blazer warrants it"}, "color_palette": "Dark navy, charcoal, black, wine red — the palette of a French bistro that opened before you were born", "budget_dupe": "A good blazer from anywhere, well-pressed dark jeans, leather shoes. Raoul''s is about the quality of your appreciation for a room that has been this good for fifty years."}, "women": {"brands": ["Isabel Marant", "Sandro", "A.P.C."], "outfit": {"top": "A French-influenced piece — a silk blouse with a subtle pattern, a good blazer over a simple top, a wrap dress in a deep colour", "bottom": "Dark slim jeans or tailored trousers", "shoes": "Leather ankle boots or a good heel", "bag": "A leather crossbody or quality clutch", "accessories": "Gold hoops, a thin necklace — the French approach applies in a French bistro opened by actual French people"}, "color_palette": "Dark navy, deep burgundy, ivory, black — bistro dinner in the SoHo that existed before SoHo", "budget_dupe": "A good vintage French-style blouse and dark jeans. Raoul''s predates every trend. Dress for the room, not the moment."}}',
true),

-- 36. Lucien
('11111111-0000-0000-0000-000000000001',
'Lucien',
'East Village',
'Continental',
'Lucien Bahaj''s tiny French bistro on First Avenue has been the après-gallery dinner destination for the East Village art world since 1998. The moules frites are non-negotiable. The room holds perhaps fifty people and the noise level approaches enjoyable chaos on weekends. The wine list is reasonable and the French staff are the correct amount of indifferent. Artists, writers, gallery owners, and the people who follow them have been eating here since before the neighbourhood changed.',
40.7253000, -73.9854000,
NULL,
3,
'{"men": {"brands": ["Vintage and considered", "The East Village art world has its own dress code"], "outfit": {"top": "A quality vintage piece or a well-chosen tee under a lived-in leather jacket or interesting blazer", "bottom": "Dark slim jeans or well-worn trousers", "shoes": "Clean boots or leather-soled loafers", "bag": "Nothing or a canvas tote", "accessories": "An interesting ring, a mechanical watch that looks like it was found rather than purchased"}, "color_palette": "Black, dark denim, olive, burgundy — the East Village art crowd''s permanent evening palette", "budget_dupe": "A vintage leather jacket and dark jeans. Lucien''s crowd values authenticity and aesthetic commitment. The clothes should look like they have a history."}, "women": {"brands": ["Vintage is the gold standard here", "Isabel Marant", "Ganni"], "outfit": {"top": "A vintage silk blouse or a deliberately interesting piece — Lucien rewards looking like you dressed with a point of view", "bottom": "High-waisted jeans or a midi skirt with some history to it", "shoes": "Leather ankle boots, always", "bag": "A small quality leather bag or an interesting vintage find", "accessories": "Stacked rings, interesting earrings, a vintage necklace — the East Village art community has the best eye for accessories in New York"}, "color_palette": "Deep burgundy, black, forest green, warm ivory — the palette of someone who has been coming to First Avenue since before it was on a list", "budget_dupe": "A great vintage find from a thrift store on the next block. Lucien''s credibility comes from the neighbourhood itself — buy something nearby on the way."}}',
true),

-- 37. Indochine
('11111111-0000-0000-0000-000000000001',
'Indochine',
'NoHo',
'Continental',
'The most enduringly glamorous restaurant in downtown New York. Indochine opened in 1984 and attracted Warhol, Basquiat, Keith Haring, and every fashion person of consequence for the next decade. The palm trees and colonial-tropical decor haven''t changed. The crowd has replenished itself while maintaining the exact same energy. The Vietnamese-inflected menu is good but secondary to the performance of being here. At 11pm on a Friday the best-looking room in New York.',
40.7254000, -73.9945000,
NULL,
5,
'{"men": {"brands": ["Saint Laurent", "Acne Studios", "Tom Ford", "Dior Homme"], "outfit": {"top": "A black slim blazer or a dark structured jacket — Indochine is one of the few downtown restaurants where looking deliberately stylish is the correct response", "bottom": "Black slim trousers or dark jeans", "shoes": "Black Chelsea boots or clean black leather", "bag": "Nothing", "accessories": "A watch with a story, a simple ring — this crowd knows what everything costs and doesn''t need reminding"}, "color_palette": "Black, dark navy, deep green — the palm trees provide the colour, your job is to look like you belong among them", "budget_dupe": "A well-fitted black blazer and dark jeans. Indochine''s glamour is in the room and the history. Your job is to not undercut it."}, "women": {"brands": ["Saint Laurent", "Celine", "Versace", "The Row"], "outfit": {"top": "A silk slip dress in ivory, champagne, or deep green, or a structured blazer over wide-leg silk trousers", "bottom": "An elegant silhouette — Indochine is the right restaurant for the dress you bought for a reason", "shoes": "A proper heel or a very elegant flat — the floor is beautiful and so is the crowd", "bag": "A small evening clutch or quality structured bag", "accessories": "Statement earrings, a thin chain — the tropical lighting here will make everything look better than it does anywhere else"}, "color_palette": "Ivory, champagne, deep emerald, black — the 1984-to-now palette of downtown glamour at its most sustained", "budget_dupe": "A great vintage silk dress or a slip dress from anywhere that drapes well. Indochine''s light is flattering to the point of generosity."}}',
true),

-- 38. Café Carmellini
('11111111-0000-0000-0000-000000000001',
'Café Carmellini',
'Flatiron',
'Power Lunch',
'Andrew Carmellini''s restaurant in the Fifth Avenue Hotel occupies a room that spent decades as a hotel ballroom and now operates as one of the most beautiful all-day dining rooms in the city. The yellow banquettes, the chandeliers, the tile floors — it reads as a grand European café that has been in continuous operation since 1909, which is more or less the truth. The pasta and the roast chicken have become reference-level. The Flatiron lunch crowd includes publishers, gallery owners, and tech people who prefer rooms with architectural integrity.',
40.7467000, -73.9882000,
NULL,
4,
'{"men": {"brands": ["Brunello Cucinelli", "Canali", "IWC", "Corthay"], "outfit": {"top": "A quality blazer in camel, tan, or soft grey over a white or cream shirt — the room''s yellow and warm-wood tones reward warm neutrals", "bottom": "Tailored trousers in stone or camel", "shoes": "Leather loafers or Oxfords in cognac or tan", "bag": "Slim leather portfolio or nothing", "accessories": "A serious watch, a pocket square in warm ivory or cream"}, "color_palette": "Camel, stone, tan, warm cream — the palette of someone who instinctively chose a table near the window", "budget_dupe": "A quality blazer in a warm neutral from anywhere, well-pressed trousers, cognac leather shoes. The room does the heavy lifting for mid-tier investment dressing."}, "women": {"brands": ["The Row", "Max Mara", "Loro Piana", "Gianvito Rossi"], "outfit": {"top": "A silk blouse in champagne, ivory, or warm rose — the yellow banquettes and warm lighting are in dialogue with your outfit", "bottom": "Tailored trousers in cream or camel, or a structured midi skirt", "shoes": "Clean pointed-toe heels or loafers in nude or cognac", "bag": "A structured leather bag in a warm tone — tan, cognac, cream", "accessories": "Gold studs or small drop earrings, a thin bracelet, simple and warm"}, "color_palette": "Champagne, ivory, warm rose, camel — the room is warm and golden and your outfit should participate in that", "budget_dupe": "A silk blouse from & Other Stories in a warm neutral, tailored trousers from COS. Café Carmellini''s room is generous to people who dress with warmth and intention."}}',
true);
