-- Miami Social Spaces — Additional Locations (v2)
-- Skips existing: The Setai, Faena Hotel, Vizcaya Museum & Gardens,
--   Pérez Art Museum Miami, Bal Harbour Shops, Soho Beach House Miami,
--   Wynwood Walls, The Bass Museum of Art, The Surf Club Restaurant
-- Adds 23 new locations.

INSERT INTO locations (city_id, name, neighborhood, category, description, latitude, longitude, photo_url, vibe_difficulty, what_to_wear, is_approved) VALUES

('11111111-0000-0000-0000-000000000003',
'The Standard Spa Miami Beach',
'Venetian Islands',
'Rooftop Bar',
'Perched on a converted 1950s motel on the Venetian Causeway, The Standard has spent two decades being the right kind of low-key. The rooftop hammam terrace, the mud lounge, and the pool scene are all decidedly anti-South Beach — which is exactly why the right people keep coming back. The après-spa crowd at the bar is more interesting than anything on Collins Avenue.',
25.7882, -80.1547,
NULL,
3,
'{"men": {"brands": ["Vilebrequin", "Frescobol Carioca", "Orlebar Brown"], "outfit": {"top": "Terry cloth shirt or vintage linen open-collar", "bottom": "Tailored swim shorts in a solid colour", "shoes": "Leather slides or bare feet", "bag": "Canvas tote", "accessories": "Minimal — nothing you can''t get wet"}, "color_palette": "Sand, white, terracotta", "budget_dupe": "H&M premium linen set with quality slides"}, "women": {"brands": ["Jacquemus", "Eres", "Ulla Johnson"], "outfit": {"top": "Bandeau or halter bikini top under a sheer linen cover-up", "bottom": "High-waisted bikini bottoms or linen wrap skirt", "shoes": "Minimalist flat sandals", "bag": "Rattan clutch or small canvas bag", "accessories": "Gold hoops, SPF lip gloss, that''s it"}, "color_palette": "Ecru, terracotta, warm olive", "budget_dupe": "Asos Premium swim with Zara linen cover-up"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'1 Hotel South Beach',
'South Beach',
'Hotel Lobby',
'Barry Sternlicht''s eco-luxury property on Collins Avenue is what happens when the environment is the aesthetic, not an afterthought. Living walls, reclaimed wood, surfboards as lobby art — it reads like a mood board for the sustainably-minded wealthy. The Watr rooftop pool deck has a strong claim as the best hotel view in South Beach. The crowd is media, wellness, and tech money.',
25.7942, -80.1303,
NULL,
3,
'{"men": {"brands": ["Norse Projects", "Patagonia", "Our Legacy"], "outfit": {"top": "Organic cotton crewneck or linen button-down", "bottom": "Technical slim trousers or premium chinos", "shoes": "Merino sneakers or leather sandals", "bag": "Minimal canvas weekender", "accessories": "Recycled-material watch, no logo visible"}, "color_palette": "Forest green, natural white, warm grey", "budget_dupe": "Uniqlo linen with Allbirds"}, "women": {"brands": ["Totême", "Veja x Mercer", "Mara Hoffman"], "outfit": {"top": "Draped organic silk top or knit tank", "bottom": "Wide-leg linen trousers or midi skirt", "shoes": "Veja trainers or Birkenstock Arizona in leather", "bag": "Natural straw or undyed canvas tote", "accessories": "Minimal gold studs, simple chain"}, "color_palette": "Sage, warm cream, raw linen", "budget_dupe": "Everlane linen with Mango resort pieces"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Versace Mansion (Casa Casuarina)',
'South Beach',
'Old Money',
'Gianni Versace bought this 1930 Mediterranean Revival mansion in 1992 and spent four years turning it into one of the most opulent private residences in the world. The gold-leaf mosaic pool — 24-carat, hand-laid — is the centrepiece. Now operating as Villa Casa Casuarina hotel and restaurant, it remains the most maximally committed address in Miami. Sunday brunch on the pool terrace is an exercise in controlled excess. Dress like you understand what you''re standing in.',
25.7762, -80.1306,
NULL,
5,
'{"men": {"brands": ["Versace", "Brioni", "Tom Ford"], "outfit": {"top": "Silk Versace baroque shirt or impeccably-cut white dress shirt", "bottom": "Tailored Brioni trousers, no belt visible", "shoes": "Velvet Versace loafers or patent Oxford", "bag": "Slim leather document case", "accessories": "Medusa head cufflinks, heavy gold watch, rings acceptable"}, "color_palette": "Gold, midnight black, Versace cobalt", "budget_dupe": "Zara premium suit with H&M baroque shirt — though nothing is a dupe here"}, "women": {"brands": ["Versace", "Valentino", "Roberto Cavalli"], "outfit": {"top": "Goddess-drape gown or structured Versace cocktail dress", "bottom": "Floor-length or thigh-high — pick one", "shoes": "Versace Medusa platform heels", "bag": "Versace La Medusa clutch", "accessories": "Gold everything — earrings, bracelets, anklet if you want it"}, "color_palette": "Gold, black, Baroque jewel tones", "budget_dupe": "Asos Luxe + costume jewellery — the occasion demands commitment regardless of budget"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Fontainebleau Miami Beach',
'Mid-Beach',
'Hotel Lobby',
'Morris Lapidus''s 1954 masterpiece invented the Miami Beach hotel as a spectacle. The sweeping curved facade, the staircase to nowhere, the iconic Lapis nightclub — the Fontainebleau has hosted Sinatra, JFK, and every significant Miami moment in between. After a billion-dollar renovation it''s once again the grandest address on Collins. The lobby alone is worth the visit. The pool situation is a world unto itself.',
25.8186, -80.1219,
NULL,
4,
'{"men": {"brands": ["Brunello Cucinelli", "Kiton", "Zegna"], "outfit": {"top": "Unstructured linen blazer over open-collar shirt", "bottom": "Tailored cream or navy trousers", "shoes": "Suede loafers — tan or white", "bag": "Slim tote or nothing", "accessories": "Understated gold watch, tan"}, "color_palette": "Cream, navy, caramel", "budget_dupe": "Massimo Dutti full look — blazer, chino, leather shoe"}, "women": {"brands": ["Zimmermann", "Cult Gaia", "Self-Portrait"], "outfit": {"top": "One-shoulder or halter cocktail top", "bottom": "Wide palazzo trousers or midi skirt", "shoes": "Block-heel sandals or strappy heels", "bag": "Structured minaudière or bamboo bag", "accessories": "Drop earrings, layered gold chains"}, "color_palette": "Ivory, gold, tropical coral", "budget_dupe": "Revolve resort pieces with ASOS Luxe accessories"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'The Biltmore Hotel',
'Coral Gables',
'Old Money',
'John Merrick built the Biltmore in 1926 to anchor his vision of Coral Gables as America''s most beautiful city. The tower was modelled on the Giralda in Seville. Al Capone kept a suite. The pool — at its completion the largest in the world — still draws the city''s establishment for Sunday tea and the annual polo season. The Biltmore operates at a register of wealth that predates the Ocean Drive era by fifty years.',
25.7257, -80.2795,
NULL,
4,
'{"men": {"brands": ["Ralph Lauren Purple Label", "Hackett London", "Anderson & Sheppard"], "outfit": {"top": "Pale blue poplin Oxford shirt, pressed", "bottom": "Cream linen trousers or khaki chinos", "shoes": "Tan brogues or white bucks", "bag": "Leather briefcase or nothing", "accessories": "Classic watch, pocket square optional"}, "color_palette": "Pale blue, cream, British tan", "budget_dupe": "Ralph Lauren Polo linen with Church''s shoes on sale"}, "women": {"brands": ["Carolina Herrera", "Oscar de la Renta", "Tory Burch"], "outfit": {"top": "Tailored blazer or structured sheath dress top", "bottom": "A-line skirt or wide-leg trousers", "shoes": "Block-heel pumps or pointed ballet flats", "bag": "Structured ladybag or saddle bag", "accessories": "Pearls or coral, tortoiseshell sunglasses"}, "color_palette": "Hibiscus coral, ivory, Coral Gables cream", "budget_dupe": "Banana Republic Heritage line with a single good-quality accessory"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Institute of Contemporary Art Miami',
'Design District',
'Art World',
'Aranguren & Gallegos''s glass pavilion is the Design District''s cultural anchor — free admission always, programming that consistently outpaces the institution''s modest size. The ICA takes risks that PAMM occasionally can''t afford to. The garden cafe is underrated. The crowd on opening nights is a curated mix of artists, gallerists, and collectors who prefer substance to spectacle — which, in Miami, is the rarest combination.',
25.8138, -80.1927,
NULL,
2,
'{"men": {"brands": ["Comme des Garçons", "Acne Studios", "Rick Owens"], "outfit": {"top": "Oversized black or off-white structured tee, or a considered shirt", "bottom": "Tailored wide-leg trousers or dark denim", "shoes": "Clean minimalist trainers or leather Derby", "bag": "Structured tote or nothing", "accessories": "One unusual ring or no accessories — both work"}, "color_palette": "Black, grey, architectural white", "budget_dupe": "COS and Arket basics — the point is composition, not logo"}, "women": {"brands": ["Marni", "Simone Rocha", "Jil Sander"], "outfit": {"top": "Marni floral print or deconstructed blouse", "bottom": "Asymmetric midi skirt or wide-leg trousers", "shoes": "Mary Janes, unexpected loafers, or sculptural sandals", "bag": "Tote or architectural mini bag", "accessories": "Interesting earrings, minimal else"}, "color_palette": "Warm abstract, dusty rose, architectural neutrals", "budget_dupe": "Zara Studio with & Other Stories accessories"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Design District Palm Court',
'Design District',
'Luxury Retail',
'The Design District''s central gathering point is an open-air luxury shopping campus that makes Beverly Hills feel provincial. Palm Court''s canopy of mosaic palm trees — a permanent installation by Bertrand Lamarche — provides the backdrop for runway boutiques, gallery spaces, and the kind of people-watching that requires no commentary. Arrive in the afternoon. Walk slowly. The point is not what you buy.',
25.8124, -80.1931,
NULL,
3,
'{"men": {"brands": ["Louis Vuitton", "Dior Men", "Celine Homme"], "outfit": {"top": "Current-season statement piece — one brand, worn simply", "bottom": "Tailored trousers or premium denim", "shoes": "Fashion-forward sneakers or current-season loafers", "bag": "Current It-bag or nothing", "accessories": "Brand-right watch, single ring"}, "color_palette": "Whatever the current season dictates", "budget_dupe": "One quality vintage piece, rest from COS — carry yourself"}, "women": {"brands": ["Chanel", "Prada", "Bottega Veneta"], "outfit": {"top": "Current season top — structured or fluid depending on the house", "bottom": "Coordinating skirt or trousers", "shoes": "It-shoe of the season", "bag": "The bag you came to show, or a classic", "accessories": "One hero piece"}, "color_palette": "Current runway palette", "budget_dupe": "Vintage find from the era you''re referencing, styled with intention"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Brickell City Centre',
'Brickell',
'Luxury Retail',
'Arquitectonica''s climate-ribbon shopping complex brought an entirely different energy to Brickell''s financial corridor — polished, accessible luxury rather than South Beach excess. Saks Fifth Avenue anchors the retail, but the real draw is the dining floor and the rooftop Happy Wine bar crowd. The clientele is the new Miami professional class: Latin American finance, tech, and the young wealthy who live in the surrounding towers.',
25.7645, -80.1931,
NULL,
2,
'{"men": {"brands": ["Hugo Boss", "Ted Baker", "Michael Kors"], "outfit": {"top": "Smart casual shirt or lightweight blazer", "bottom": "Dark chinos or tailored jeans", "shoes": "Clean leather loafers or dress sneakers", "bag": "Slim backpack or briefcase", "accessories": "Watch, minimal"}, "color_palette": "Navy, charcoal, crisp white", "budget_dupe": "Zara Man premium line — this crowd is aspirational, not established"}, "women": {"brands": ["Kate Spade", "Tory Burch", "Veronica Beard"], "outfit": {"top": "Silk cami or structured blouse", "bottom": "Midi skirt or tailored trousers", "shoes": "Block-heel mules or pointed flats", "bag": "Structured shoulder bag", "accessories": "Delicate layered gold"}, "color_palette": "Coral, white, gold", "budget_dupe": "Banana Republic with a single good bag"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'The Edition Miami Beach',
'Mid-Beach',
'Hotel Lobby',
'Ian Schrager''s most restrained Miami property sits inside a restored 1955 building and operates as a rebuttal to the excess of the surrounding competition. The lobby is spare and perfect. Matador — the basement nightclub — is genuinely difficult to get into. The pool deck, ice rink, and bowling alley underground create a private world that has little to do with the beach outside. The crowd skews fashion and international money.',
25.8061, -80.1236,
NULL,
4,
'{"men": {"brands": ["Acne Studios", "Tom Ford", "A.P.C."], "outfit": {"top": "Clean white tee or slim black rollneck under a structured blazer", "bottom": "Trim black or dark navy trousers", "shoes": "White minimal trainers or black Chelsea boots", "bag": "Nothing, or a very small leather card case", "accessories": "The less, the better — a single good watch"}, "color_palette": "Black, white, warm grey", "budget_dupe": "COS monochrome with Sandro accessories"}, "women": {"brands": ["The Row", "Bottega Veneta", "Totême"], "outfit": {"top": "Bias-cut slip or structured minimal dress", "bottom": "Nothing below the knee or nothing above — The Row logic", "shoes": "The Row kitten mules or Bottega padded sandals", "bag": "The Row clutch or Bottega pouch", "accessories": "Single sculptural piece — earring or cuff"}, "color_palette": "Ecru, blush, soft black", "budget_dupe": "Arket slip dress, H&M Studio, single vintage accessory"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Mandarin Oriental Miami',
'Brickell Key',
'Hotel Lobby',
'Marooned on Brickell Key — a private island in Biscayne Bay — the Mandarin Oriental operates as Miami''s most quietly serious luxury hotel. The bay views from the pool and Brickell Key Steak are among the best in the city. The clientele is corporate luxury and visiting dignitaries rather than fashionistas. The spa consistently ranks among the best in North America. Arrive via the causeway as if you own a unit in the building across the street.',
25.7702, -80.1889,
NULL,
4,
'{"men": {"brands": ["Loro Piana", "Zegna", "Canali"], "outfit": {"top": "Polo shirt or open-collar dress shirt in silk or fine cotton", "bottom": "Pressed cream or grey trousers", "shoes": "Tan loafers or white leather sneakers", "bag": "Slim leather portfolio or nothing", "accessories": "Patek Philippe or equivalent, nothing else"}, "color_palette": "Ivory, camel, slate grey", "budget_dupe": "Ralph Lauren Polo shirt with well-pressed chinos and a single quality leather shoe"}, "women": {"brands": ["Oscar de la Renta", "Akris", "St. John"], "outfit": {"top": "Silk blouse or structured jersey top", "bottom": "Midi skirt or tailored trousers in a neutral", "shoes": "Pointed-toe pumps or kitten heel mules", "bag": "Classic ladybag or structured shoulder bag", "accessories": "Pearl or gold earrings, watch"}, "color_palette": "Soft white, champagne, pale grey", "budget_dupe": "Ann Taylor for the silhouette, then invest in one real accessory"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Four Seasons Surf Club',
'Surfside',
'Weekend Aristocrat',
'The original Surf Club was the most exclusive address in 1930s Miami — Frank Sinatra, Winston Churchill, and the Duke and Duchess of Windsor were regulars. The Four Seasons restoration by Thierry Despont kept the original Spanish Colonial cabanas and amplified everything else. Thomas Keller''s restaurant is a separate landmark. The beach club, the pool, the discretion — this is old money''s answer to the South Beach hotel.',
25.8719, -80.1232,
NULL,
5,
'{"men": {"brands": ["Vilebrequin", "Brunello Cucinelli", "Bather"], "outfit": {"top": "Linen shirt in a pale stripe, worn open over trunks poolside", "bottom": "Quality swim trunks — nothing with visible branding", "shoes": "Hermès Oran sandals or leather slides", "bag": "Waxed canvas tote", "accessories": "Good watch, sun on your face"}, "color_palette": "Pale blue, white, navy", "budget_dupe": "La Redoute linen shirt with Polo Ralph Lauren trunks"}, "women": {"brands": ["La Perla", "Marysia", "Zimmermann"], "outfit": {"top": "Marysia scallop-edge one-piece or La Perla underwire", "bottom": "High-waisted bikini bottom or matching brief", "shoes": "Flat leather sandals or barefoot", "bag": "Straw Métier tote or nothing", "accessories": "Gold huggie earrings — small, nothing that catches sun"}, "color_palette": "Sand dollar, warm white, seafoam", "budget_dupe": "Anine Bing one-piece, Cult Gaia sandals — the key is proportion, not price"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Acqualina Resort & Residences',
'Sunny Isles Beach',
'Weekend Aristocrat',
'Sunny Isles''s answer to the ultra-luxury European resort. Acqualina''s Mediterranean architecture, three pools, and Aquanox spa have made it the preferred address for Latin American and Eastern European wealth that wants privacy over fashion week adjacency. The ESPA spa is world-class. The beach is controlled and quiet. The clientele ranges from legitimately famous to legitimately wealthy — frequently both.',
25.9339, -80.1219,
NULL,
5,
'{"men": {"brands": ["Dolce & Gabbana Beach", "Frescobol Carioca", "Ermenegildo Zegna"], "outfit": {"top": "Terry cloth zip-up or linen open shirt", "bottom": "Premium swim shorts — no logos, strong colour or subtle print", "shoes": "Hermès or high-quality leather slides", "bag": "Monogrammed beach tote", "accessories": "Watch in yellow gold"}, "color_palette": "Mediterranean blue, white, gold", "budget_dupe": "Polo Ralph Lauren terry set — the resort aesthetic is about ease, not edge"}, "women": {"brands": ["Eres", "Vix", "Melissa Odabash"], "outfit": {"top": "Eres structured one-piece or Melissa Odabash bandeau", "bottom": "Wrap sarong in a solid or subtle print", "shoes": "Aquazzura flat sandals", "bag": "Fendi or Goyard beach tote", "accessories": "Thin gold chain, oversized shell earrings"}, "color_palette": "Champagne, azure, warm coral", "budget_dupe": "Calzedonia premium swimwear, Zara resort cover-up — focus on fit"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Eden Roc Miami Beach',
'Mid-Beach',
'Hotel Lobby',
'Morris Lapidus''s other masterpiece — the Fontainebleau''s rival since 1956. The Eden Roc''s volcanic rock grotto pool and the NOBU EDEN ROC restaurant give it a distinctly more dramatic personality than its neighbour. The celebrity clientele that used to book Sammy Davis Jr. and Marlene Dietrich now books differently but no less deliberately. The rooftop gym has an unobstructed ocean view that makes every workout feel cinematic.',
25.8199, -80.1215,
NULL,
4,
'{"men": {"brands": ["Dolce & Gabbana", "Roberto Cavalli", "Versace"], "outfit": {"top": "Printed short-sleeve shirt — bold or refined, no middle ground", "bottom": "Tailored trousers or premium swim shorts", "shoes": "Leather sandals or loafers", "bag": "Nothing or small crossbody", "accessories": "Gold chain, rings, confidence"}, "color_palette": "Ocean blue, volcanic black, gold", "budget_dupe": "H&M x designer collaboration pieces — the Eden Roc rewards flair over subtlety"}, "women": {"brands": ["Johanna Ortiz", "Camilla", "Adriana Degreas"], "outfit": {"top": "Printed wrap top or structured bikini in a bold print", "bottom": "Wrap skirt or palazzo trousers", "shoes": "Platform sandals or wedge espadrilles", "bag": "Straw clutch or chain bag", "accessories": "Chandelier earrings, bangles"}, "color_palette": "Tropical jewels — fuchsia, cobalt, emerald", "budget_dupe": "Agua by Agua Bendita — the print is the investment"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Nobu Hotel Miami Beach',
'Mid-Beach',
'Continental',
'Nobu Matsuhisa''s hotel and restaurant concept entered Miami at the Eden Roc and brought with it the precisely calibrated combination of Japanese minimalism and global celebrity that defines the brand. The Nobu Miami menu is the full expression — black cod miso, yellowtail jalapeño, sake programme — delivered in a room that manages to feel intimate despite its size. The crowd is deliberate: entertainment industry, international business, people who eat at Nobu in every city.',
25.8195, -80.1215,
NULL,
4,
'{"men": {"brands": ["Issey Miyake", "Comme des Garçons Homme", "Stone Island"], "outfit": {"top": "Architectural tee or minimal printed shirt in Japanese cotton", "bottom": "Slim tailored trousers or premium dark denim", "shoes": "Clean minimal sneakers or leather slip-ons", "bag": "Nothing or slim card wallet", "accessories": "Single sculptural ring or bracelet"}, "color_palette": "Black, charcoal, warm white", "budget_dupe": "Uniqlo premium cotton with COS tailoring"}, "women": {"brands": ["Zimmermann", "Helmut Lang", "Proenza Schouler"], "outfit": {"top": "Fluid silk cami or minimal bodysuit", "bottom": "High-waisted wide trousers or an elegant midi", "shoes": "Pointed-toe heels or contemporary flat sandals", "bag": "Structured envelope clutch", "accessories": "Architectural earring — one, not both"}, "color_palette": "Black, cream, warm bronze", "budget_dupe": "& Other Stories for the fluid pieces, then a single real shoe"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Sugar Rooftop at EAST Miami',
'Brickell',
'Rooftop Bar',
'On the 40th floor of the EAST Miami hotel in Brickell, Sugar is the city''s reigning rooftop. The Brickell skyline and bay views are unmatched at this elevation; the cocktail programme is one of the most serious in Miami; the crowd from Thursday through Saturday is the financial and creative class that lives in the surrounding towers and treats this as their living room. The golden retriever energy stops at the lift doors.',
25.7616, -80.1906,
NULL,
3,
'{"men": {"brands": ["Paul Smith", "Reiss", "Ted Baker"], "outfit": {"top": "Open-collar smart shirt or lightweight blazer over tee", "bottom": "Slim chinos or dark tailored trousers", "shoes": "Leather Chelsea boots or clean loafers", "bag": "Nothing or small leather card case", "accessories": "Watch, no tie"}, "color_palette": "Navy, white, caramel", "budget_dupe": "Zara Man tailored pieces — the rooftop rewards sharp over expensive"}, "women": {"brands": ["Reformation", "Veronica Beard", "Ulla Johnson"], "outfit": {"top": "Floaty cami or structured strapless top", "bottom": "Slit midi skirt or wide-leg trousers", "shoes": "Strappy heeled sandals or pointed-toe mules", "bag": "Small chain shoulder bag", "accessories": "Gold layered chains, statement earrings"}, "color_palette": "Warm terracotta, off-white, deep burgundy", "budget_dupe": "Mango Evening line — this crowd is polished, not pedigreed"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Sweet Liberty Drinks & Supply Co.',
'Miami Beach',
'Continental',
'John Lermayer''s Miami Beach institution — winner of more World''s Best Bar recognition than any other address in Florida — operates without the pretension those awards might suggest. Sweet Liberty is genuinely welcoming: the bar team knows the classics and the originals equally, the crowd mixes industry people with anyone who knows to come here, and the late-night energy is pure Miami without the velvet rope. Go for a Daiquiri. Stay for three hours.',
25.7897, -80.1321,
NULL,
2,
'{"men": {"brands": ["Saturdays NYC", "Corridor", "Todd Snyder"], "outfit": {"top": "Well-fitting tee or an open linen shirt", "bottom": "Quality straight-leg jeans or chinos", "shoes": "Clean white sneakers or suede boots", "bag": "Nothing", "accessories": "Minimal — a watch if you wear one"}, "color_palette": "Washed blue, natural white, tan", "budget_dupe": "A single well-chosen vintage piece — Sweet Liberty has earned the authentic"}, "women": {"brands": ["Madewell", "Reformation", "Sézane"], "outfit": {"top": "Slip top or fitted cotton tee", "bottom": "Straight-leg jeans or flowy shorts", "shoes": "Sandals or retro trainers", "bag": "Small crossbody or clutch", "accessories": "A couple of gold rings, that''s all"}, "color_palette": "Faded denim, warm white, coral", "budget_dupe": "Vintage Levi''s, a good top, and money saved for the cocktails"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Komodo',
'Brickell',
'Power Lunch',
'David Grutman''s five-floor Brickell destination is the most transacted power-dining room in Miami. Asian-inspired menu, rooftop lounge, and a calendar that aligns with every significant business visit to the city. The first floor at lunch is where deals get made between the second and main courses. The rooftop on weekends belongs to a different crowd. Both have the same dress code: arrive looking like you can afford to be there.',
25.7649, -80.1898,
NULL,
3,
'{"men": {"brands": ["Hugo Boss", "Theory", "Ralph Lauren Purple Label"], "outfit": {"top": "Fitted dress shirt or subtle-pattern button-down — jacket preferred at lunch", "bottom": "Well-tailored dark trousers or premium chinos", "shoes": "Oxford or Derby in black or dark tan leather", "bag": "Slim leather briefcase or portfolio", "accessories": "Quality watch, nothing flashy"}, "color_palette": "Charcoal, white, deep navy", "budget_dupe": "Suit Supply for the silhouette — in Brickell, the cut matters more than the brand"}, "women": {"brands": ["Roland Mouret", "Diane von Furstenberg", "L''Agence"], "outfit": {"top": "Structured blazer or wrap dress", "bottom": "Pencil skirt or straight trousers", "shoes": "Pointed-toe heels or polished block heels", "bag": "Structured tote or ladybag", "accessories": "Stud earrings, watch or single bracelet"}, "color_palette": "Power navy, burgundy, clean white", "budget_dupe": "BCBG or Banana Republic for the power silhouette — invest in the shoes"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Joia Beach',
'Watson Island',
'Weekend Aristocrat',
'On Watson Island between downtown and South Beach, Joia Beach is the city''s most scenically situated beach club — Biscayne Bay on one side, Miami skyline on the other, with the causeway traffic invisible from the sand. The food programme is better than expected. The day-bed situation requires advance booking. The crowd is a genuine cross-section of Miami pleasure-seekers who discovered the spot before it became fully stratified.',
25.7758, -80.1714,
NULL,
3,
'{"men": {"brands": ["Orlebar Brown", "Vilebrequin", "Bather"], "outfit": {"top": "Light linen shirt or branded resort tee", "bottom": "Quality swim trunks — mid-length, solid or minimal print", "shoes": "Leather sandals or flip flops from a brand that understands flip flops", "bag": "Canvas or mesh beach bag", "accessories": "Watch that can get wet, sunglasses"}, "color_palette": "Sky blue, coral, sand", "budget_dupe": "H&M Conscious linen with good sunglasses as the investment"}, "women": {"brands": ["Agua Bendita", "Vix Swimwear", "Onia"], "outfit": {"top": "Printed bikini top or bandeau", "bottom": "High-cut bikini bottoms with a loose cover skirt", "shoes": "Flat leather sandals or bare feet", "bag": "Rattan tote", "accessories": "Anklet, minimal chain, sunglasses"}, "color_palette": "Tropical print, warm sand, sky", "budget_dupe": "Target x boutique brand collab swimwear — the bay doesn''t check tags"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Mr. C Coconut Grove',
'Coconut Grove',
'Hotel Lobby',
'Ignazio and Maggio Cipriani''s boutique hotel brings the family''s particular brand of Venetian aristocratic hospitality to Coconut Grove''s sailboat-and-banyan-tree quietness. The rooftop pool and Bellini Bar operate at a register that Miami Beach can''t quite replicate: European sophistication without the performance. The Coconut Grove Sailing Club is visible from the terrace. The clientele is mature, international, and reliably well-dressed.',
25.7289, -80.2387,
NULL,
3,
'{"men": {"brands": ["Cifonelli", "Lardini", "Pal Zileri"], "outfit": {"top": "Unstructured Italian linen blazer over a fine-knit polo", "bottom": "Tailored cream or pale grey trousers", "shoes": "Driving shoes or tan leather loafers", "bag": "Nothing or a leather satchel", "accessories": "A watch your grandfather would have worn"}, "color_palette": "Coastal white, navy, warm stone", "budget_dupe": "Massimo Dutti linen blazer with Polo Ralph Lauren polo — the Grove forgives brand substitutions"}, "women": {"brands": ["Loro Piana", "Agnona", "Max Mara"], "outfit": {"top": "Silk shirt or fine-knit top", "bottom": "Wide-leg linen trousers or a fluid midi skirt", "shoes": "Leather flat sandals or espadrille wedge", "bag": "Woven leather bag or Cipriani-appropriate bucket", "accessories": "Single gold bangle, quality sunglasses"}, "color_palette": "Ivory, warm olive, soft navy", "budget_dupe": "Uniqlo linen plus one investment piece — the Grove is about ease, not status"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Juvia Rooftop',
'South Beach',
'Rooftop Bar',
'Eight floors above the Lincoln Road mall, Juvia''s wraparound terrace gives you the most complete Miami Beach view: ocean east, bay west, skyline north, Art Deco south. The Peruvian-Japanese-French fusion menu is earnest. The cocktail programme is excellent. The crowd is a reliable South Beach mix of Brazilian tourists, European fashionistas, and locals who booked three weeks ago. Sunset is the only reservation time worth considering.',
25.7910, -80.1398,
NULL,
3,
'{"men": {"brands": ["Gucci", "Dsquared2", "Dolce & Gabbana"], "outfit": {"top": "Bold printed short-sleeve shirt or a clean white linen", "bottom": "Slim trousers or premium dark denim", "shoes": "Loafers or leather sandals", "bag": "Nothing", "accessories": "Gold chain if it''s yours to wear"}, "color_palette": "White, ocean blue, warm gold", "budget_dupe": "Zara Man weekend edit — sunset makes everything look expensive"}, "women": {"brands": ["Agua Bendita", "SemSem", "Johanna Ortiz"], "outfit": {"top": "Off-shoulder ruffle top or halter in a tropical print", "bottom": "Maxi skirt or wide palazzo trousers that move in the wind", "shoes": "Platform wedge sandals or block-heel mules", "bag": "Small embroidered or beaded clutch", "accessories": "Layered necklaces, hoop earrings"}, "color_palette": "Fuchsia, cobalt, warm sunset orange", "budget_dupe": "Shein designer-inspired prints actually work here — the sunset light is flattering"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Pharrell''s Goodtime Hotel',
'South Beach',
'Hotel Lobby',
'Pharrell Williams and David Grutman''s Washington Avenue hotel is Miami''s most fully realised statement of aesthetic intent: primary colours, butterfly prints, a pool deck that functions as the city''s best daytime party, and a Strawberry Moon rooftop that belongs to a different night than the one you planned. The commitment is total. Irony doesn''t survive the lobby. Come dressed for where you actually want to end up.',
25.7765, -80.1344,
NULL,
4,
'{"men": {"brands": ["Billionaire Boys Club", "Human Made", "Casablanca"], "outfit": {"top": "Casablanca silk shirt or statement graphic tee", "bottom": "Relaxed tailored trousers or premium shorts", "shoes": "Fresh Nike Dunks or Casablanca court shoes", "bag": "Chest bag or nothing", "accessories": "Whatever you''ve been waiting to wear"}, "color_palette": "Primary bold — cobalt, lemon yellow, vermillion", "budget_dupe": "Vintage colourblock pieces from any era — Goodtime rewards aesthetic, not spending"}, "women": {"brands": ["Versace", "Moschino", "Kim Shui"], "outfit": {"top": "Colour-saturated crop top or printed halter", "bottom": "Mini skirt or matching colourblock set", "shoes": "Platform trainers or colour-matched heels", "bag": "Mini structured bag in a primary colour", "accessories": "Bold everything — this is the right occasion"}, "color_palette": "Anything saturated — this is not the place for neutral restraint", "budget_dupe": "Vintage 90s pieces, PrettyLittleThing for the maximalist pieces — Goodtime''s whole premise is accessible joy"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Ocean Drive Art Deco Strip',
'South Beach',
'Old Money',
'The ten blocks of Ocean Drive from 5th to 15th Street constitute the most complete collection of Art Deco architecture in the world — Hohauser, Dixon, Polevitzky, and their contemporaries built this corridor between 1930 and 1942. The neon, the pastel facades, the overhang awnings, the terrazzo floors — it''s all original or restored original. Walk it at 7am before the café chairs fill. Walk it again at midnight when the neon is lit. The architecture is the social space.',
25.7800, -80.1302,
NULL,
2,
'{"men": {"brands": ["Ralph Lauren", "Todd Snyder", "Reyn Spooner"], "outfit": {"top": "Vintage-style guayabera or open linen shirt", "bottom": "Linen trousers or well-cut shorts", "shoes": "White canvas sneakers or leather sandals", "bag": "Nothing", "accessories": "Wayfarers, tan"}, "color_palette": "Pastel — seafoam, coral pink, pale yellow", "budget_dupe": "Any vintage shop on Española Way will supply the right reference for under $30"}, "women": {"brands": ["Anna Sui", "Zimmermann", "Rhode"], "outfit": {"top": "Printed cotton dress or halter top in a period-appropriate palette", "bottom": "Anything with movement — the point is to walk", "shoes": "Comfortable wedge sandals or retro trainers", "bag": "Small vintage-style shoulder bag", "accessories": "Cat-eye sunglasses, headscarves accepted"}, "color_palette": "Art Deco pastels — coral, aqua, cream, flamingo pink", "budget_dupe": "Thrift the entire look — Ocean Drive was built by people who understood that style precedes spending"}}'::jsonb,
true),

('11111111-0000-0000-0000-000000000003',
'Rusty Pelican',
'Key Biscayne',
'Continental',
'On the Rickenbacker Causeway with the full Miami skyline behind you and the bay in front, the Rusty Pelican offers the city''s most cinematic waterfront dining view. The seafood programme is reliably strong. The Sunday brunch is the meal that Miami''s Coconut Grove and Brickell contingent has been eating for forty years. Come at sunset, sit on the terrace, order the whole fish, and watch the city lights come on across the water.',
25.7350, -80.1661,
NULL,
3,
'{"men": {"brands": ["Peter Millar", "Vineyard Vines", "Faherty"], "outfit": {"top": "Crisp white linen shirt or navy polo", "bottom": "Tan or cream chinos — pressed", "shoes": "Boat shoes or tan leather loafers", "bag": "Nothing", "accessories": "Watch that works with boat shoes"}, "color_palette": "Nautical — navy, white, red accent", "budget_dupe": "J.Crew linen with a single quality shoe — Key Biscayne reads classic American"}, "women": {"brands": ["Lilly Pulitzer", "Tory Burch", "Sail to Sable"], "outfit": {"top": "Printed sundress or silk blouse in a coastal pattern", "bottom": "Sundress or resort trousers", "shoes": "Wedge espadrilles or leather sandals", "bag": "Straw tote or structured shoulder bag", "accessories": "Gold seahorse earrings or shell necklace, sunglasses"}, "color_palette": "Coastal — coral, white, seafoam, navy", "budget_dupe": "Lilly Pulitzer outlet pieces — the Key Biscayne crowd practically invented the look"}}'::jsonb,
true);
