-- London — Additional Locations
-- Skips existing: The Ritz Hotel Palm Court, Claridge's Lobby Bar, The Connaught Bar,
--   The Savoy American Bar, Annabel's, The Wolseley, Fortnum & Mason,
--   Burlington Arcade, The Wallace Collection
-- Adds 41 new locations.

INSERT INTO locations (city_id, name, neighborhood, category, description, latitude, longitude, photo_url, vibe_difficulty, what_to_wear, is_approved) VALUES

('11111111-0000-0000-0000-000000000002',
'The Dorchester',
'Mayfair',
'Hotel Lobby',
'The Dorchester has occupied the east side of Hyde Park since 1931 and has not particularly changed its opinion of itself since. The Promenade lobby — all gilded mirrors, fresh flowers the size of small trees, and afternoon light from the park — is one of the great London public rooms. The Bar at The Dorchester is a serious place for a serious drink. Arrive as though the car is waiting.',
51.5076, -0.1527,
NULL,
4,
'{"men": {"brands": ["Huntsman", "Brioni", "Patek Philippe", "George Cleverley"], "outfit": {"top": "A dark suit in navy or charcoal — The Dorchester is a jacket situation at all hours", "bottom": "Matching trousers, pressed to a crease", "shoes": "Black or dark tan cap-toe Oxfords, mirror-polished", "bag": "Nothing or a slim leather attaché", "accessories": "Patek Philippe or Jaeger-LeCoultre, a silk pocket square in cream, no other jewelry"}, "color_palette": "Navy, charcoal, white — the palette of someone who has stayed in Park Lane-facing rooms before", "budget_dupe": "A well-tailored dark suit from SuitSupply worn with properly polished shoes. The Dorchester''s staff will treat you identically regardless of the label inside the jacket."}, "women": {"brands": ["Oscar de la Renta", "Roland Mouret", "Cartier", "Gianvito Rossi"], "outfit": {"top": "A structured day dress in a jewel tone or a tailored suit in ivory or pale grey", "bottom": "(dress) or slim tailored trousers", "shoes": "A proper heel — court shoe or pointed kitten heel in nude or black", "bag": "A structured top-handle in black or tan, small and serious", "accessories": "Cartier Love or Panthère, pearl drop earrings, a single thin bracelet"}, "color_palette": "Deep sapphire, ivory, champagne, blush — The Dorchester''s flowers set the colour standard and they are always extraordinary", "budget_dupe": "A beautifully cut dress from LK Bennett or a secondhand Roland Mouret. The Dorchester rewards silhouette above everything else."}}',
true),

('11111111-0000-0000-0000-000000000002',
'The Lanesborough',
'Hyde Park Corner',
'Hotel Lobby',
'Built as St George''s Hospital in 1828 and converted by Grace Leo-Andrieu into a Regency house hotel in 1991, The Lanesborough operates at a register of luxury that does not feel the need to announce itself. The Library Bar serves some of the finest cocktails in London in a room of mahogany shelves and firelight. The butler service is genuine. The clientele is the international wealthy — the kind who give their location as Hyde Park Corner.',
51.5020, -0.1533,
NULL,
5,
'{"men": {"brands": ["Anderson & Sheppard", "Kiton", "A. Lange & Söhne", "John Lobb"], "outfit": {"top": "A Savile Row suit or a blazer of comparable quality — The Lanesborough is a building that rewards proper dressing", "bottom": "Matching or coordinated trousers in dark grey or navy", "shoes": "John Lobb or Edward Green in black, mirror shine", "bag": "Nothing", "accessories": "A. Lange & Söhne or Patek Philippe, a real silk tie for evening, a pocket square always"}, "color_palette": "Midnight navy, charcoal, cream — the palette of a private house staffed by people who know what you want before you do", "budget_dupe": "A very well-fitted dark suit from anywhere, impeccably pressed and worn with real leather shoes. The Lanesborough Library Bar is intimate and warmly lit — fabric quality matters less than fit and intention."}, "women": {"brands": ["Emilia Wickstead", "Victoria Beckham", "Van Cleef & Arpels", "Manolo Blahnik"], "outfit": {"top": "A silk evening dress or a structured cocktail dress in a deep colour — midnight blue, emerald, or black", "bottom": "(dress) or wide-leg silk trousers for a more contemporary read", "shoes": "A pointed-toe heel in satin or leather", "bag": "A small evening bag in leather or satin — structured, unencumbered", "accessories": "Van Cleef or Cartier, a statement earring in one ear if you wish, delicate chain"}, "color_palette": "Midnight blue, deep emerald, ivory, champagne — Regency grandeur interpreted for the present", "budget_dupe": "A silk dress sourced secondhand from a good consignment shop. The Library Bar is candlelit and generous. A beautiful dress from any decade reads correctly here."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Brown''s Hotel',
'Mayfair',
'Hotel Lobby',
'The oldest hotel in London, opened in 1837 by James Brown, formerly Lord Byron''s manservant. Rudyard Kipling wrote part of The Jungle Book here. Agatha Christie set a murder here. The English Tea Room does the most serious afternoon tea in Mayfair — better than The Ritz by a significant margin, with a third the queue. The Donovan Bar, named after Terence Donovan, is unexpectedly good. Arrive as a regular, even if it''s your first time.',
51.5094, -0.1421,
NULL,
4,
'{"men": {"brands": ["Gieves & Hawkes", "Ralph Lauren Purple Label", "IWC", "Crockett & Jones"], "outfit": {"top": "A blazer in navy or heritage tweed over a cream or pale blue shirt — Brown''s rewards the country-in-town register", "bottom": "Dark flannel or cavalry twill trousers", "shoes": "Crockett & Jones or Church''s in tan or dark brown, well-polished", "bag": "Nothing or a leather-handled document case", "accessories": "IWC Portugieser or an antique pocket watch — Brown''s is the right hotel for a pocket watch"}, "color_palette": "Navy, heritage tweed, tan — 1837 to present, uninterrupted", "budget_dupe": "A good tweed blazer from a charity shop near Marylebone (they exist), pressed dark trousers from M&S, Church''s shoes from their own sale. Brown''s is old enough to recognise good breeding regardless of recent provenance."}, "women": {"brands": ["Mulberry", "Temperley London", "Asprey", "L.K. Bennett"], "outfit": {"top": "A printed silk blouse in a Liberty or botanical print, or a fine cashmere in rose or sage", "bottom": "A tailored A-line skirt in a muted print or slim trousers in warm grey", "shoes": "A low block heel or court shoe in tan or soft burgundy", "bag": "A Mulberry Bayswater — this is literally the correct bag for Brown''s Hotel", "accessories": "Pearl or coral earrings, a thin gold chain, a silk scarf if the weather demands it"}, "color_palette": "Sage, dusty rose, ivory, tan — the English country house come to Albemarle Street", "budget_dupe": "John Lewis does the cashmere and the court shoe at exactly the right price for Brown''s. A Mulberry Bayswater from eBay in tan completes the look with total authenticity."}}',
true),

('11111111-0000-0000-0000-000000000002',
'The Beaumont',
'Mayfair',
'Hotel Lobby',
'Jeremy King''s hotel in Brown Hart Gardens opened in 2014 in a 1926 building and immediately became what The Savoy and Claridge''s are to their respective clienteles but for a younger, more discreet money. The Colony Grill Room is the best hotel restaurant in London for American-style grill food done properly. GOAT — Antony Gormley''s room-sized sculpture — is in the building. The whole place operates quietly and with extraordinary conviction.',
51.5134, -0.1473,
NULL,
4,
'{"men": {"brands": ["Favourbrook", "Timothy Everest", "Rolex", "Gaziano & Girling"], "outfit": {"top": "A beautifully cut blazer in midnight navy or dark green — The Beaumont rewards considered dressing rather than formal dressing", "bottom": "Dark tailored trousers or premium dark jeans for the bar", "shoes": "A quality leather shoe in dark tan or black, nothing casual", "bag": "Nothing or a very slim card holder", "accessories": "Rolex Explorer or a vintage Omega, a pocket square in a muted colour"}, "color_palette": "Midnight navy, dark green, ivory — a 1920s American hotel filtered through the best British taste", "budget_dupe": "A well-cut dark blazer and premium dark jeans from anywhere, properly fitted. The Beaumont''s Colony Grill celebrates the kind of dressing where the intention matters as much as the execution."}, "women": {"brands": ["The Row", "Toteme", "Cartier", "Aquazzura"], "outfit": {"top": "A silk or crepe blouse in ivory or deep navy, or a structured minimal dress", "bottom": "Tailored wide-leg trousers in cream or charcoal", "shoes": "A pointed-toe heel or clean loafer in tan or black", "bag": "A structured leather bag — The Row or anything without visible branding", "accessories": "Cartier Love bracelet, simple gold earrings, a thin chain"}, "color_palette": "Ivory, deep navy, camel — quiet luxury at its most considered", "budget_dupe": "COS or Arket for the wide-leg trouser and blouse combination. One good quality bag. The Beaumont''s lighting is warm and the room forgiving."}}',
true),

('11111111-0000-0000-0000-000000000002',
'The Ned',
'City of London',
'Hotel Lobby',
'A 1924 former Midland Bank headquarters designed by Edwin Lutyens, converted by Nick Jones and the Soho House group into a members'' club and hotel of staggering architectural ambition. The banking hall alone — all original marble columns, gilded ceiling, and now eight restaurants — is one of the most extraordinary rooms in London. Non-members can eat in the restaurants. The lobby is free. It is worth seeing for the architecture regardless of anything else.',
51.5137, -0.0921,
NULL,
3,
'{"men": {"brands": ["Reiss", "Paul Smith", "Uniform Wares", "Grenson"], "outfit": {"top": "A sharp navy or charcoal blazer or a Soho House-adjacent quality shirt — The Ned is members'' club smart rather than Mayfair formal", "bottom": "Dark slim trousers or premium dark jeans", "shoes": "Clean leather Derby or Chelsea boot", "bag": "A slim leather tote or nothing", "accessories": "A considered watch — Uniform Wares or a vintage Seiko reads correctly here"}, "color_palette": "Navy, charcoal, dark tan — the City of London''s palette adapted for people who work in creative industries", "budget_dupe": "Paul Smith does the exact look for The Ned at a fraction of the Savile Row equivalent. A blazer and good jeans. The banking hall will make any outfit look significant."}, "women": {"brands": ["Reformation", "Reiss", "Astley Clarke", "& Other Stories"], "outfit": {"top": "A silk wrap dress or a structured blouse in a jewel tone — the banking hall''s gilded ceiling rewards colour", "bottom": "(dress) or tailored wide-leg trousers in dark navy or emerald", "shoes": "A modest heel or clean pointed-toe flat", "bag": "A quality leather bag without excessive branding", "accessories": "Gold stud earrings, a delicate necklace, minimal and intentional"}, "color_palette": "Emerald, deep navy, ivory — the Lutyens building''s gilt and marble pulls everything toward grandeur", "budget_dupe": "A Reformation wrap dress or a good blouse from & Other Stories. The architecture provides most of the atmosphere — your job is to not undercut it."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Rosewood London',
'Holborn',
'Hotel Lobby',
'Converted from the 1914 Pearl Assurance headquarters on High Holborn, Rosewood London has one of the most spectacular hotel lobbies in the city — a triple-height atrium with an original copper dome and a staircase of extraordinary proportions. The Holborn Dining Room has the best pie in London (this is not debatable). The Scarfes Bar is a serious late-night destination with Scarfe drawings covering every wall.',
51.5177, -0.1176,
NULL,
3,
'{"men": {"brands": ["Oliver Spencer", "Paul Smith", "Nomos", "Tricker''s"], "outfit": {"top": "A quality blazer in a warm earth tone — camel, tobacco, rust — responding to the building''s copper and marble", "bottom": "Dark tailored trousers or slim dark jeans", "shoes": "Leather brogues or Derby in tan or dark brown", "bag": "A leather tote or document case", "accessories": "A Nomos Tangente or vintage watch, a simple signet ring"}, "color_palette": "Tobacco, camel, rust, dark navy — the Edwardian civic building aesthetic interpreted for today", "budget_dupe": "Oliver Spencer sale items are made for this aesthetic. A quality blazer in a warm tone, dark jeans, leather brogues. The Rosewood''s interiors are genuinely magnificent and elevate every outfit."}, "women": {"brands": ["Ulla Johnson", "Saloni", "Monica Vinader", "Russell & Bromley"], "outfit": {"top": "A floral or warm-toned dress — the building''s copper and warm stone reward earthy florals", "bottom": "(dress) or wide-leg trousers in rust or tobacco", "shoes": "Ankle boots in cognac or a low block heel", "bag": "A structured leather bag in a warm tone", "accessories": "Monica Vinader gold hoops, a layered necklace, a ring or two"}, "color_palette": "Rust, copper, warm ivory, dark navy — the building''s own palette is the instruction", "budget_dupe": "A floral dress from Anthropologie or Boden in warm tones. Leather ankle boots from any good high street brand. The Rosewood atrium does the rest."}}',
true),

('11111111-0000-0000-0000-000000000002',
'5 Hertford Street',
'Mayfair',
'Old Money',
'Robin Birley''s members'' club at 5 Hertford Street has been the most exclusive address in Mayfair nightlife since 2012. You cannot get in without membership or the escort of a member. You should walk past it on a Friday evening and observe who is arriving. The green door, the Georgian facade, the discreet brass plate — it is everything a private members'' club should look like from the outside, which is most of what most people will see.',
51.5096, -0.1490,
NULL,
5,
'{"men": {"brands": ["Huntsman", "Holland & Holland", "Patek Philippe", "George Cleverley"], "outfit": {"top": "A proper suit or dinner jacket — this is after-dark Mayfair and the dress code is enforced", "bottom": "Matching trousers, no exceptions", "shoes": "Black Oxfords, polished until they reflect", "bag": "Nothing", "accessories": "Patek Philippe, pocket square, possibly a signet ring — nothing else"}, "color_palette": "Black, midnight navy, white — London late-night at its most formal", "budget_dupe": "You cannot enter without a member. Walk past looking like someone who was once a member and didn''t renew for reasons of their own choosing."}, "women": {"brands": ["Alexander McQueen", "Stella McCartney", "Bulgari", "Christian Louboutin"], "outfit": {"top": "A cocktail dress in black, midnight blue, or deep emerald — the kind you save for occasions that justify it", "bottom": "(dress) or a silk jumpsuit with a structured jacket", "shoes": "A real heel — this is the venue that justifies Christian Louboutin", "bag": "A small evening clutch, preferably in satin or beaded fabric", "accessories": "A statement piece — one significant earring or cuff, not both"}, "color_palette": "Black, deep emerald, midnight — Mayfair after dark requires full commitment to the occasion", "budget_dupe": "The LARP here is to walk past looking like you''re on your way somewhere equally exclusive. A beautiful coat and the right shoes are enough for the pavement."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Dukes Bar',
'St James''s',
'Continental',
'The bar at Dukes Hotel on St James''s Place has been making arguably the best martini in London since the 1970s, when Ian Fleming — a regular — was said to have inspired the shaken-not-stirred instruction. The bar is the size of a drawing room and serves a maximum of two martinis per person. The barmen in white jackets bring the trolley to you. You are drinking history.',
51.5055, -0.1420,
NULL,
4,
'{"men": {"brands": ["Turnbull & Asser", "Hackett", "Jaeger-LeCoultre", "Crockett & Jones"], "outfit": {"top": "A blazer or suit jacket — Dukes is St James''s and the register here is club formality without the ostentation", "bottom": "Dark flannel or charcoal trousers", "shoes": "Black or dark tan Oxford, no suede at evening", "bag": "Nothing", "accessories": "Jaeger-LeCoultre Reverso or any quality dress watch, no other accessories — this bar is about simplicity and restraint"}, "color_palette": "Navy, charcoal, cream — the palette of a man who has ordered a martini the same way for thirty years", "budget_dupe": "A dark suit or blazer from anywhere well-fitted, good leather shoes. Dukes Bar is small, intimate, and not interested in your label. It is interested in your composure."}, "women": {"brands": ["Amanda Wakeley", "LK Bennett", "Cartier", "Manolo Blahnik"], "outfit": {"top": "A silk blouse in champagne or pale ivory, or a tailored shift dress in navy", "bottom": "(dress) or slim tailored trousers in dark navy", "shoes": "A modest heel in black or nude satin", "bag": "A small structured clutch — this is a two-martini bar, nothing larger is appropriate", "accessories": "Cartier or pearl, a thin bracelet, small earrings"}, "color_palette": "Champagne, ivory, midnight navy — the two-martini drawing room demands restraint and elegance", "budget_dupe": "A well-cut dark dress from LK Bennett or Reiss. One real piece of jewelry. Dukes Bar is about the quality of your conversation, not the brand of your clothes."}}',
true),

('11111111-0000-0000-0000-000000000002',
'The American Bar at The Stafford',
'St James''s',
'Continental',
'The Stafford''s American Bar is covered — ceiling, walls, every surface — in objects left by generations of American guests since the Second World War: baseball caps, license plates, photographs, Zippo lighters, signed dollar bills. The result is one of the most warmly eccentric bar rooms in London. Order a classic cocktail. Read the ceiling. Understand that some bars are collections as much as they are rooms.',
51.5053, -0.1418,
NULL,
3,
'{"men": {"brands": ["Ralph Lauren", "Polo", "Seiko", "Sanders"], "outfit": {"top": "A navy blazer or a quality shirt — the American Bar is St James''s in formality but warmer in spirit", "bottom": "Dark chinos or pressed dark jeans", "shoes": "Leather loafers or clean Derby", "bag": "Nothing", "accessories": "A watch with a history — a vintage Seiko or a family heirloom is more appropriate here than a new Patek"}, "color_palette": "Navy, cream, old leather — the palette of a room that has been collecting things since 1946", "budget_dupe": "A navy blazer from anywhere, dark trousers, leather shoes. The Stafford Bar is the warmest room in St James''s and forgiving about everything except visible disrespect."}, "women": {"brands": ["Ralph Lauren", "Hobbs", "Monica Vinader", "Russell & Bromley"], "outfit": {"top": "A classic blouse or a fine knit in a warm tone — navy, burgundy, camel", "bottom": "Slim trousers or a tailored A-line skirt", "shoes": "A low block heel or loafer in tan or burgundy", "bag": "A structured leather bag or a quality clutch", "accessories": "Gold hoops, a chain necklace — classics that don''t try too hard"}, "color_palette": "Navy, burgundy, camel, cream — a bar that has been collecting Americana since before you were born rewards warmth over fashion", "budget_dupe": "Hobbs and John Lewis do this look precisely. A quality blouse and good trousers. The American Bar will make you feel that you''ve been coming here for years regardless."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Mark''s Club',
'Mayfair',
'Old Money',
'Mark Birley''s private dining club at 46 Charles Street has been one of the most exclusive addresses in Mayfair since 1966. You cannot enter without membership. Walk Charles Street in the early evening and observe the cars outside, the discreet entrance, the impeccable Georgian facade, and the quality of coats disappearing through the door. The exterior is the LARP. The interior requires an invitation that cannot be engineered.',
51.5083, -0.1446,
NULL,
5,
'{"men": {"brands": ["Huntsman", "Brioni", "Patek Philippe", "Foster & Son"], "outfit": {"top": "A Savile Row suit — this is not a blazer situation. Mark''s Club is the definitive London private dining club and the dress code is implicit and absolute.", "bottom": "Matching suit trousers", "shoes": "Black or dark tan hand-lasted Oxfords", "bag": "Nothing", "accessories": "Patek Philippe, silk tie, pocket square, a signet ring if inherited"}, "color_palette": "Charcoal, midnight navy, white — the private Mayfair dining club dress code has not changed in fifty years because it was correct from the beginning", "budget_dupe": "Walk Charles Street. Observe. Look like someone returning to collect a forgotten umbrella. The LARP is entirely exterior."}, "women": {"brands": ["Chanel", "Valentino", "Cartier", "Manolo Blahnik"], "outfit": {"top": "An evening dress or a beautifully cut cocktail dress — Mark''s is not a casual dinner venue", "bottom": "(dress)", "shoes": "A proper heel, always", "bag": "An evening clutch", "accessories": "A significant piece — a good brooch, real stones, the kind of jewelry that has been cleaned recently"}, "color_palette": "Black, deep jewel tones, ivory — the private club palette that has never needed revision", "budget_dupe": "You are walking past. Wear a beautiful coat with excellent shoes. A Georgian street in Mayfair on a winter evening is a LARP in itself."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Harry''s Bar',
'Mayfair',
'Continental',
'The London outpost of the Venetian institution on South Audley Street has been a Mayfair fixture since 1979. The food is rich, Italian, and unapologetic. The room is small, the tables are close, the clientele is old Mayfair money and the people who orbit it. The Bellini is the obvious order. The veal is the correct order. Both are acceptable simultaneously.',
51.5075, -0.1533,
NULL,
4,
'{"men": {"brands": ["Brioni", "Zegna", "Patek Philippe", "Berluti"], "outfit": {"top": "A dark suit or an excellent blazer — Harry''s Bar is formal Italian dining and the room requires it", "bottom": "Tailored trousers, pressed", "shoes": "Dark leather Oxfords or monk straps", "bag": "Nothing", "accessories": "Patek Philippe or Cartier Santos, a pocket square, no tie required but a collar that can support one"}, "color_palette": "Midnight navy, charcoal, cream — Italian-Venetian formality in a Mayfair room", "budget_dupe": "A well-cut dark suit from SuitSupply, leather shoes polished. Harry''s Bar is about the quality of your presence at the table, not the name of your tailor."}, "women": {"brands": ["Dolce & Gabbana", "Valentino", "Bvlgari", "Aquazzura"], "outfit": {"top": "A cocktail dress in black, deep red, or champagne — Harry''s Bar rewards a certain Italian glamour", "bottom": "(dress) or wide-leg silk trousers with a jewelled top", "shoes": "A proper heel", "bag": "A small structured clutch or minaudière", "accessories": "Statement earrings, a good bracelet — Harry''s is the right venue for your gold"}, "color_palette": "Deep red, black, champagne, gold — the palette of a Venetian institution that has been consistent since 1931", "budget_dupe": "A beautiful vintage cocktail dress. Harry''s Bar in London is the kind of room where a well-worn dress from the right decade reads as better than something new."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Scott''s Mayfair',
'Mayfair',
'Power Lunch',
'The Mount Street restaurant has been feeding the right people since 1851 — originally as an oyster warehouse near Piccadilly, now as the most reliable power lunch and power dinner address in Mayfair. The oak-panelled room, the lobster tank, and the quality of the fish are constants. The pavement tables in summer are the best outdoor dining in Mayfair. The clientele on any given lunchtime includes several people you have heard of.',
51.5102, -0.1504,
NULL,
4,
'{"men": {"brands": ["Turnbull & Asser", "Ralph Lauren Purple Label", "Rolex", "Church''s"], "outfit": {"top": "A blazer or suit jacket — Scott''s lunch is a working occasion and the standard is business formality", "bottom": "Dark navy or charcoal trousers, pressed", "shoes": "Church''s or Crockett & Jones in tan or black, polished", "bag": "A slim briefcase or portfolio", "accessories": "Rolex Datejust or Submariner, a pocket square, possibly a tie"}, "color_palette": "Navy, charcoal, cream — Mayfair power lunch in a room that has been serving it since Victoria''s time", "budget_dupe": "A good dark blazer and pressed trousers from M&S Autograph. Church''s shoes from their own sale. Scott''s rewards looking like you belong rather than looking like you tried."}, "women": {"brands": ["Roland Mouret", "Victoria Beckham", "Cartier", "Gianvito Rossi"], "outfit": {"top": "A structured blazer or tailored dress in a confident colour — the Mount Street lunch crowd does not do neutral", "bottom": "Tailored trousers or a knee-length pencil skirt", "shoes": "A pointed-toe heel in a quality leather", "bag": "A structured tote or ladybag that closes properly", "accessories": "Cartier, a silk scarf, pearl earrings or gold — the Scott''s terrace in summer is photographed by people who notice these things"}, "color_palette": "Deep teal, burgundy, camel, navy — Mount Street power colours that have been winning arguments since 1851", "budget_dupe": "Reiss or Hobbs for the tailored dress or blazer. The Mount Street clientele have opinions but they are principally about the lobster."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Sexy Fish',
'Mayfair',
'Continental',
'Richard Caring''s 2015 restaurant in Berkeley Square is the most visually committed dining room in London: a 25-foot aquarium wall, coral sculptures by Damien Hirst, bronze mermaids by Frank Gehry, and a Coral Room of staggering excess. The Japanese-influenced menu is genuinely good. The cocktail programme is excellent. It is the correct level of maximalism — never kitsch because the budget was too large for kitsch.',
51.5112, -0.1481,
NULL,
4,
'{"men": {"brands": ["Tom Ford", "Saint Laurent", "Audemars Piguet", "Berluti"], "outfit": {"top": "A dark slim blazer or a dressed-up casual jacket — Sexy Fish is fashion-forward without requiring a suit", "bottom": "Dark slim trousers or premium black jeans", "shoes": "A quality leather shoe or fashion-adjacent boot in black", "bag": "Nothing", "accessories": "AP Royal Oak or a design-forward watch, a single ring — the Damien Hirst corals in the room will compete with anything too elaborate"}, "color_palette": "Black, dark navy, with one deliberate flash of colour — the room provides the spectacle, your job is to provide a coherent counterpoint", "budget_dupe": "A fitted black blazer from anywhere, black jeans, good shoes. Sexy Fish''s room is strong enough that it elevates every outfit in it."}, "women": {"brands": ["Saint Laurent", "Versace", "Messika", "Louboutin"], "outfit": {"top": "A dress that justifies the room — something silk, something strong, something that understands this is a spectacle and participates accordingly", "bottom": "(dress) or a fashion-forward separates combination", "shoes": "A heel with conviction — the floor is marble and the room notices", "bag": "A small structured bag or a clutch that matches the occasion", "accessories": "Statement earrings or a body chain — Sexy Fish is the right venue for the piece you bought at the gallery opening"}, "color_palette": "Black, deep coral, emerald, gold — the aquarium wall and the coral sculptures are the décor, and they are not subtle", "budget_dupe": "One great vintage piece in a strong colour or texture. Sexy Fish''s lighting is flattering and the room so overwhelming that a single confident choice reads as a complete outfit."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Sketch',
'Mayfair',
'Art World',
'Pierre Gagnaire and Mourad Mazouz''s 2002 Conduit Street institution contains several distinct rooms at different registers: the Gallery (pink velvet, David Shrigley drawings), the Glade (enchanted forest), the Lecture Room (two Michelin stars), and the egg-pod loos that every visitor photographs. It is simultaneously an art installation, a Michelin-starred restaurant, and a place to have afternoon tea in pink velvet. Come for the room as much as the food.',
51.5121, -0.1427,
NULL,
3,
'{"men": {"brands": ["Acne Studios", "Dries Van Noten", "Nomos", "Common Projects"], "outfit": {"top": "Something considered and slightly unexpected — the Gallery''s pink velvet rewards deliberate dressing rather than conventional dressing", "bottom": "Dark tailored trousers or premium dark jeans", "shoes": "Clean minimal shoes or an interesting boot", "bag": "Nothing or a minimal tote", "accessories": "A design-forward watch, possibly a considered ring"}, "color_palette": "Black, deep grey, with one intentional colour note — the room is pink and opinionated and will not compete with your pattern", "budget_dupe": "COS or Arket for the architectural basics, one interesting vintage piece. Sketch rewards an eye rather than a budget."}, "women": {"brands": ["Simone Rocha", "Molly Goddard", "Charlotte Tilbury (the makeup)", "Miu Miu"], "outfit": {"top": "Something that responds to the pink room — a contrasting strong colour or an equally opulent texture", "bottom": "(dress) or a skirt with volume", "shoes": "An interesting shoe — the egg-pod loos are photographed alongside your feet", "bag": "An architectural or whimsical bag — Sketch is the venue where your Loewe Puzzle or JW Anderson Moon bag makes sense", "accessories": "A deliberate statement piece — Sketch is the venue where accessories function as art"}, "color_palette": "A colour that confronts the pink room — cobalt, citron, deep forest green, or lean fully into the pink and go monochromatic", "budget_dupe": "A vintage piece in a strong colour from a charity shop or Depop. Sketch''s Gallery rewards imagination and the egg-pod loos photograph any outfit dramatically well."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Bob Bob Ricard',
'Soho',
'Continental',
'The Russian-British Soho institution famous for the brass press-for-champagne button at every table. The food is excellent — Beef Wellington, Lobster Mac, caviar in a tin — and the booths are individually lit. The entire room is gold, cobalt, and Deco. Press the button. The waiter arrives. It has been this way since 2008 and should remain so indefinitely.',
51.5129, -0.1393,
NULL,
3,
'{"men": {"brands": ["Ozwald Boateng", "Paul Smith", "Cartier Santos", "Grenson"], "outfit": {"top": "A blazer with personality — Bob Bob Ricard is not the place for anonymous navy. A windowpane check, a velvet, a deep colour.", "bottom": "Dark tailored trousers", "shoes": "A quality leather shoe with a degree of character — brogue or monk strap", "bag": "Nothing", "accessories": "Cartier Santos or a vintage Omega, a pocket square that earns its keep"}, "color_palette": "Deep cobalt, gold, midnight — the room is Deco and opinionated and your outfit should acknowledge it", "budget_dupe": "A blazer with genuine character sourced from a good charity shop or Depop. Dark trousers and leather shoes. The champagne button is the experience regardless of what you paid for your jacket."}, "women": {"brands": ["Self-Portrait", "Roland Mouret", "Monica Vinader", "Kurt Geiger"], "outfit": {"top": "A dress that justifies pressing the champagne button — something structured, something with colour, something that reads as occasion", "bottom": "(dress) or a sequined or satin separates combination", "shoes": "A heel — the booth seating and the Deco room make heels feel obligatory", "bag": "A small evening bag or clutch — the booths have their own shelf", "accessories": "Gold and bold — the room is gold and cobalt and it pulls your accessories toward the dramatic"}, "color_palette": "Gold, cobalt, ivory, deep red — the room''s own palette is an instruction", "budget_dupe": "A self-portrait dress at their own sale prices or secondhand. Bob Bob Ricard is celebratory in a way that makes any beautiful outfit feel appropriate regardless of the label."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Rules',
'Covent Garden',
'Continental',
'Rules opened in 1798, which makes it the oldest restaurant in London and one of the oldest in the world. Thomas Hardy ate here. Charles Dickens ate here. Graham Greene had a regular table. The menu has not substantially changed: game, pies, puddings, claret. The interior — cartoons, paintings, antlers, burgundy banquettes — has not changed either. The experience of eating in a room where significant people have eaten for 226 years is not reproducible elsewhere.',
51.5121, -0.1236,
NULL,
3,
'{"men": {"brands": ["Hackett", "Barbour", "Rolex", "Loake"], "outfit": {"top": "A blazer or a tweed jacket — Rules is the oldest restaurant in London and the dress code is inherited rather than stated", "bottom": "Dark trousers or cavalry twill in mid-brown", "shoes": "A quality brogue or Derby in tan or dark brown", "bag": "Nothing", "accessories": "A dress watch — vintage preferred — and possibly a signet ring. Rules is a room for inherited objects."}, "color_palette": "Burgundy, tobacco, dark navy — the colours of a dining room that has been open since 1798", "budget_dupe": "A good tweed jacket from a British charity shop, dark trousers, leather shoes. Rules is about the accumulated atmosphere of 226 years and your contribution to it."}, "women": {"brands": ["Boden", "LK Bennett", "Mulberry", "Russell & Bromley"], "outfit": {"top": "A classic printed dress or a tailored blouse with a skirt — Rules rewards traditional rather than fashion-forward", "bottom": "(dress) or an A-line skirt in a muted print", "shoes": "A block heel or court shoe", "bag": "A quality structured bag — a Mulberry is extremely correct here", "accessories": "Pearl earrings, a thin gold necklace, a silk scarf if the weather is appropriate"}, "color_palette": "Forest green, burgundy, camel, ivory — the English country house brought to Covent Garden in 1798 and never relocated", "budget_dupe": "Boden does the printed dress for Rules perfectly. A quality bag from any source. The experience of eating game pie in the oldest restaurant in London is the thing that cannot be budget-duped."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Wiltons',
'St James''s',
'Old Money',
'The oldest restaurant in St James''s, established 1742. Wiltons serves oysters, game, and the kind of silence that comes from four generations of the same families eating at the same tables. The room on Jermyn Street has the quality of a private club that accidentally admits non-members if they book far enough in advance. Order the native oysters. Speak quietly. Leave by 9pm.',
51.5061, -0.1381,
NULL,
5,
'{"men": {"brands": ["Anderson & Sheppard", "Turnbull & Asser", "Patek Philippe", "John Lobb"], "outfit": {"top": "A Savile Row suit or blazer — Wiltons is St James''s at its most historically charged and the dress code is absolute", "bottom": "Matching trousers or dark grey flannels", "shoes": "Black or dark tan cap-toe Oxfords, properly polished", "bag": "Nothing", "accessories": "A dress watch — Patek Philippe or antique — a pocket square in white linen"}, "color_palette": "Charcoal, navy, cream — the St James''s palette unchanged since 1742", "budget_dupe": "A dark well-fitted suit from anywhere, properly pressed. One real pair of polished leather shoes. Wiltons will seat you if you look like you understand why you''re there."}, "women": {"brands": ["Emilia Wickstead", "Chanel", "Van Cleef & Arpels", "Manolo Blahnik"], "outfit": {"top": "A tailored day dress or a classic suit — Wiltons has a dress code that existed before the word ''smart-casual'' was invented", "bottom": "(dress) or a skirt suit", "shoes": "A court shoe or modest heel in navy or black", "bag": "A small structured bag that closes properly", "accessories": "Pearl earrings, a simple gold chain, a brooch if it''s genuine"}, "color_palette": "Navy, cream, pale grey — the St James''s dining room palette, calibrated for several centuries", "budget_dupe": "A well-cut dress from LK Bennett in navy or cream. Quality shoes. Wiltons rewards the quality of your composure above anything you''re wearing."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Brasserie Zédel',
'Soho',
'Continental',
'A restored 1930s French brasserie in the basement of what was once the Regent Palace Hotel on Sherwood Street. At under £30 for three courses and a glass of house wine, it offers the best value in central London for a genuinely beautiful room. The ceiling is painted gold, the columns are marble, the portions are Parisian, and the steak frites are correct. No pretension. Remarkable value. A room that has earned its own mythology.',
51.5117, -0.1364,
NULL,
2,
'{"men": {"brands": ["Whatever you own that reads as considered"], "outfit": {"top": "A smart casual piece — a blazer over a good shirt, or a quality merino rollneck", "bottom": "Dark jeans or slim chinos, pressed", "shoes": "Clean leather shoes or Chelsea boots", "bag": "Nothing", "accessories": "A watch, nothing more required"}, "color_palette": "Dark navy, charcoal, white — Parisian brasserie dressing in a Soho basement that happens to be magnificent", "budget_dupe": "Brasserie Zédel is the budget dupe. The room is glorious and the price of dinner makes dressing well feel like the appropriate reciprocation."}, "women": {"brands": ["Sézane", "& Other Stories", "Astley Clarke"], "outfit": {"top": "A silk blouse or a quality knit — something French-inflected and not trying too hard", "bottom": "Straight-leg dark jeans or tailored trousers", "shoes": "Clean ankle boots or leather flats — this is a Soho basement, not a gala", "bag": "A quality crossbody or tote", "accessories": "Simple gold hoops, a thin necklace — the room is the statement"}, "color_palette": "Navy, cream, stripe — the brasserie palette that Parisian women have been executing effortlessly since 1930", "budget_dupe": "Brasserie Zédel is the complete package: a magnificent room, correct food, democratic pricing. The only investment required is a clean shirt and a willingness to sit with your back straight."}}',
true),

('11111111-0000-0000-0000-000000000002',
'J Sheekey',
'Covent Garden',
'Continental',
'The Covent Garden seafood institution has occupied its lane off St Martin''s Court since 1896. The theatre crowd has been eating here before and after curtain since then: the fish pie is perhaps the finest in London, the oysters are consistently excellent, and the room — wood panelling, signed theatrical photographs, intimate tables — is a genuine period room. Order champagne. Order oysters. Thank whoever recommended it.',
51.5120, -0.1261,
NULL,
3,
'{"men": {"brands": ["Paul Smith", "Hackett", "Rolex", "Grenson"], "outfit": {"top": "A blazer or smart jacket — J Sheekey is theatre-adjacent and the dress code reflects it: smart, considered, not overdressed", "bottom": "Dark trousers or premium dark jeans", "shoes": "Clean leather shoes or a good boot", "bag": "Nothing or a slim portfolio if pre-theatre", "accessories": "A watch, a simple ring — J Sheekey is not a jewellery occasion"}, "color_palette": "Navy, charcoal, white — the Covent Garden theatre crowd''s permanent evening palette", "budget_dupe": "A blazer from anywhere well-fitted, dark trousers, leather shoes. J Sheekey''s warmth and the fish pie make any smart outfit feel right."}, "women": {"brands": ["Reiss", "Rixo", "Monica Vinader", "Russell & Bromley"], "outfit": {"top": "A printed silk dress or a quality blouse with tailored trousers — theatrical without being theatrical", "bottom": "(dress) or slim dark trousers", "shoes": "A modest heel or clean pointed-toe flat", "bag": "A quality clutch or small structured bag for the theatre", "accessories": "Gold hoops, a simple necklace, no elaborate accessorising"}, "color_palette": "Burgundy, navy, deep floral prints — the Covent Garden evening palette that has been correct since the Edwardian period", "budget_dupe": "A Rixo printed dress does J Sheekey exactly at a reasonable price point. Leather shoes from Russell & Bromley. The fish pie and the champagne are the experience."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Cecconi''s Mayfair',
'Mayfair',
'Continental',
'The Burlington Gardens Cecconi''s is the London iteration of the Soho House group''s most civilised concept: Venetian all-day dining in a room of black-and-white marble and bottle-green banquettes. Breakfast here is a ritual, lunch is a meeting, dinner is a long conversation. The Bellini arrives properly. The pasta is reliable. The crowd is creative industry Mayfair — which is to say, well-dressed people who know better than to mention who they work for.',
51.5087, -0.1410,
NULL,
3,
'{"men": {"brands": ["A.P.C.", "Tom Ford", "Rolex", "Common Projects"], "outfit": {"top": "A considered blazer or a quality shirt — Cecconi''s rewards looking like you come regularly rather than like you dressed up to come", "bottom": "Dark slim trousers or premium dark jeans", "shoes": "Clean leather loafers or minimal white shoes", "bag": "Nothing or a very slim wallet", "accessories": "Rolex or a clean design-forward watch, one ring"}, "color_palette": "Black, bottle green, cream — the Cecconi''s interior palette is the instruction", "budget_dupe": "A quality blazer and dark jeans from anywhere, leather loafers. Cecconi''s crowd is creative and warm. The Bellini is the uniform."}, "women": {"brands": ["Toteme", "Isabel Marant", "Cartier", "Aquazzura"], "outfit": {"top": "A silk blouse in cream or soft colour, or a quality knit under a structured blazer", "bottom": "Wide-leg tailored trousers or straight-leg dark jeans", "shoes": "Clean leather loafers or a pointed-toe flat", "bag": "A quality structured bag — no excessive branding", "accessories": "Simple gold hoops, a thin bracelet, a minimal necklace"}, "color_palette": "Cream, camel, bottle green, black — Venetian minimalism with a Mayfair context", "budget_dupe": "A silk blouse from & Other Stories, good dark jeans, leather loafers. Cecconi''s all-day format means breakfast through dinner is equally forgiving and equally correct."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Daphne''s',
'Chelsea',
'Continental',
'The Draycott Avenue Italian has been feeding Chelsea for decades with the conviction that nothing needs to change when everything is already correct. The room is warm and the pasta is the kind that arrives without drama and is immediately perfect. The clientele is Chelsea old money, the parents of Chelsea old money, and the occasional person from Kensington who feels that Daphne''s forgives the postcode deviation.',
51.4921, -0.1682,
NULL,
3,
'{"men": {"brands": ["Brunello Cucinelli", "Loro Piana", "Rolex", "Church''s"], "outfit": {"top": "A cashmere crewneck or a quality sport coat over a fine shirt — Daphne''s is Chelsea dinner, relaxed but never casual", "bottom": "Dark slim trousers or well-cut dark jeans", "shoes": "Leather loafers or a clean brogue in tan or brown", "bag": "Nothing", "accessories": "Rolex Datejust, a simple ring, nothing louder than the restaurant"}, "color_palette": "Camel, navy, cream — Chelsea dinner, inherited good taste", "budget_dupe": "A cashmere crewneck from Uniqlo and well-cut dark jeans with leather loafers. Daphne''s rewards the kind of dressing where everything fits properly and nothing is new."}, "women": {"brands": ["The Row", "Vince", "Cartier", "Gianvito Rossi"], "outfit": {"top": "A silk blouse in cream or blush, or a fine cashmere in camel under a tailored blazer", "bottom": "Wide-leg trousers or a midi skirt in a warm tone", "shoes": "Clean pointed-toe flats or a low block heel", "bag": "A quality leather bag that has been used — Daphne''s is the wrong venue for something new and unscuffed", "accessories": "Cartier Love bracelet, pearl studs, a thin gold chain"}, "color_palette": "Cream, camel, blush, warm ivory — Chelsea dinner in a room that has been perfect for thirty years", "budget_dupe": "A silk blouse from & Other Stories, well-cut trousers from COS, leather shoes. Daphne''s rewards relaxed confidence."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Locanda Locatelli',
'Marylebone',
'Continental',
'Giorgio Locatelli''s Seymour Street restaurant has held a Michelin star since 2002 and has never needed a rebrand, a concept refresh, or an influencer campaign. The risotto and the pasta are reference-level. The room — by David Collins — is warm, dark, and serious about hospitality in the Italian sense. The sommelier knows more about Italian wine than you do and will not make you feel bad about this.',
51.5162, -0.1569,
NULL,
4,
'{"men": {"brands": ["Zegna", "Canali", "IWC", "Berluti"], "outfit": {"top": "A jacket — Locanda Locatelli is a Michelin-starred Italian restaurant and the room asks for formality without demanding a suit", "bottom": "Dark tailored trousers", "shoes": "Leather shoes in black or dark tan", "bag": "Nothing", "accessories": "IWC or Rolex, a pocket square, no tie required"}, "color_palette": "Dark navy, charcoal, cream — Italian fine dining in Marylebone, which has its own specific gravity", "budget_dupe": "A good blazer and dark trousers from anywhere well-fitted. Locanda Locatelli''s reputation is built on the quality of the hospitality. Your contribution is dressing appropriately."}, "women": {"brands": ["Victoria Beckham", "Emilia Wickstead", "Bulgari", "Jimmy Choo"], "outfit": {"top": "A structured dress in a warm colour — terracotta, deep gold, forest green", "bottom": "(dress) or silk trousers with a quality blouse", "shoes": "A modest heel in leather", "bag": "A small structured bag", "accessories": "Gold earrings, a bracelet, a thin necklace — Italian fine dining rewards Italian dressing logic"}, "color_palette": "Terracotta, deep gold, forest green, black — the palette that makes Italian food taste better", "budget_dupe": "A well-cut dress from Reiss in a warm tone. One real piece of jewelry. Locanda Locatelli''s warmth makes everyone feel they belong regardless of budget."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Bellamy''s',
'Mayfair',
'Old Money',
'The small Bruton Place brasserie has been one of the most consistently correct Mayfair lunches since Gavin Rankin opened it in 2001. The room is French, the portions are correct, the wine list is Burgundy-heavy, and the clientele is Mayfair establishment — the kind of people who are there every week and have their table. Booking is necessary. The lobster bisque is necessary.',
51.5109, -0.1450,
NULL,
4,
'{"men": {"brands": ["Hackett", "Ralph Lauren Purple Label", "Rolex", "Crockett & Jones"], "outfit": {"top": "A blazer in navy or camel over a plain shirt — Bellamy''s is old Mayfair lunch and the standard is established rather than fashion", "bottom": "Cavalry twill or pressed dark trousers", "shoes": "Crockett & Jones in tan or dark brown, always polished", "bag": "A slim leather briefcase if necessary", "accessories": "Rolex or a quality dress watch, a pocket square, possibly a tie"}, "color_palette": "Navy, camel, cream — the Mayfair brasserie palette that predates the concept of a mood board", "budget_dupe": "A quality blazer from M&S Autograph, pressed cavalry twill trousers, Church''s shoes from eBay. Bellamy''s is about the quality of your confidence at the table."}, "women": {"brands": ["Mulberry", "LK Bennett", "Cartier", "Russell & Bromley"], "outfit": {"top": "A classic silk blouse or a cashmere twinset — Bellamy''s is the Mayfair brasserie where the twinset is not ironic", "bottom": "A tailored A-line skirt or slim trousers in camel or navy", "shoes": "A low court shoe or kitten heel", "bag": "A Mulberry Bayswater or any quality structured leather bag", "accessories": "Pearl studs, a gold chain, a Cartier Love bracelet if you have one"}, "color_palette": "Camel, cream, navy, pale gold — the French brasserie palette as interpreted by the Mayfair establishment", "budget_dupe": "John Lewis cashmere twinset, LK Bennett court shoe, a secondhand Mulberry. Bellamy''s rewards the kind of dressing that has been done this way for thirty years."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Bar Termini',
'Soho',
'Continental',
'Marco Arrigo and Tony Conigliaro''s tiny Soho bar on Old Compton Street makes the best negroni in London. The bar holds perhaps twenty people standing, is modelled on a 1930s Italian railway bar, and serves aperitivo hour with the conviction of someone who has seen a Milanese aperitivo hour and wishes to replicate it precisely in W1. Come at 6pm. Order the negroni. Stand.',
51.5131, -0.1303,
NULL,
3,
'{"men": {"brands": ["Corridor NYC", "Incotex", "Swatch x Blancpain", "Tricker''s"], "outfit": {"top": "A quality crewneck or a linen short-sleeve shirt in a warm tone — Italian aperitivo bar in Soho is relaxed but deliberate", "bottom": "Slim dark jeans or chinos", "shoes": "Leather loafers or clean minimal shoes", "bag": "Nothing — the bar is small", "accessories": "A simple watch, a ring if it''s your habit"}, "color_palette": "Warm white, navy, terracotta — the Milanese aperitivo palette, transported to Old Compton Street", "budget_dupe": "A quality linen shirt and dark jeans. Bar Termini is about the negroni and the twenty-person intimacy. Your outfit is a secondary consideration."}, "women": {"brands": ["Sézane", "Jacquemus", "Monica Vinader", "Mango"], "outfit": {"top": "A linen blouse or a silk top in a warm tone — the Italian railway bar aesthetic rewards warm simplicity", "bottom": "Straight-leg jeans or a simple midi skirt", "shoes": "Leather loafers or sandals", "bag": "A small crossbody — the bar is standing-room, nothing large", "accessories": "Small gold hoops, a thin ring or two"}, "color_palette": "Terracotta, warm white, olive — Italian in feeling, Soho in context", "budget_dupe": "A good linen shirt from Uniqlo and straight jeans. Bar Termini charges appropriately for the negroni and nothing else matters."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Quo Vadis',
'Soho',
'Continental',
'The Dean Street institution opened in 1926 — Karl Marx lived in a flat upstairs for eleven years, which is something the menu does not mention. The Quo Vadis that exists now is the one that Jeremy Lee transformed: modern British cooking at a high level, a warm and intelligent room, and the best devilled kidneys in London. It has the quality of a private club that admits anyone who books, which is the only kind of private club worth attending.',
51.5142, -0.1327,
NULL,
3,
'{"men": {"brands": ["Margaret Howell", "Oliver Spencer", "Uniform Wares", "Sanders"], "outfit": {"top": "A quality crewneck or a well-cut shirt in a warm tone — Quo Vadis is smart Soho, not Mayfair formal", "bottom": "Dark straight-leg jeans or slim chinos", "shoes": "Leather Chelsea boots or clean Derbies", "bag": "Nothing or a slim canvas tote", "accessories": "A considered watch, possibly a signet ring"}, "color_palette": "Camel, navy, dark grey — the British intellectual''s dinner palette", "budget_dupe": "A quality crewneck from Uniqlo, dark jeans, leather boots. Quo Vadis''s crowd is warm and intelligent and more interested in the devilled kidneys than your brand."}, "women": {"brands": ["Toast", "Vince", "Astley Clarke", "Grenson"], "outfit": {"top": "A quality blouse in a warm print or a fine knit in rust or sage", "bottom": "Straight-leg dark jeans or wide-leg trousers in a warm tone", "shoes": "Leather ankle boots or pointed-toe flats", "bag": "A worn leather tote or small crossbody", "accessories": "Gold hoops, a simple ring stack, a thin necklace"}, "color_palette": "Rust, sage, camel, dark navy — British modern dining in a Dean Street that still has a history", "budget_dupe": "Toast on sale or any quality basics in warm tones. Quo Vadis rewards genuine warmth over fashion correctness."}}',
true),

('11111111-0000-0000-0000-000000000002',
'The French House',
'Soho',
'Continental',
'The Dean Street pub has been the centre of Soho''s bohemian life since the 1940s. Dylan Thomas, Francis Bacon, Lucian Freud, Jeffrey Bernard, and the entire cast of post-war London bohemianism drank here. The rules are still in force: no television, no music, no mobile phones, half-pints only at the bar (the exception to this last rule is a pint of Guinness). The upstairs dining room is genuinely excellent. The downstairs is a reminder that a pub can be a civilisation.',
51.5141, -0.1329,
NULL,
3,
'{"men": {"brands": ["Whatever you own that has been lived in"], "outfit": {"top": "A quality but worn-in piece — a corduroy jacket, a good shirt with history, a fine rollneck from years ago", "bottom": "Dark jeans or moleskin trousers", "shoes": "Clean leather boots or Oxfords with some mileage", "bag": "Nothing or a canvas tote with something interesting in it", "accessories": "A mechanical watch that is not new, a ring that has been on your hand for years"}, "color_palette": "Dark greens, tobacco, black — the Soho bohemian palette that has been correct since 1945", "budget_dupe": "The French House is the original budget dupe. Francis Bacon drank here on the proceeds of paintings he had not yet sold. The pub does not care about your finances."}, "women": {"brands": ["Vintage is the correct provenance here"], "outfit": {"top": "A vintage silk blouse or a quality worn piece — the French House rewards the look of someone who has been thinking about other things", "bottom": "Dark jeans or a midi skirt with some age to it", "shoes": "Leather boots, ideally with a history", "bag": "A small leather crossbody or a canvas bag with character", "accessories": "Interesting rings accumulated over years, earrings with a story"}, "color_palette": "Black, dark floral, tobacco — the palette of someone who reads for pleasure and drinks red wine", "budget_dupe": "The French House charges pub prices. The ambience is approximately 80 years of the right people making the right decisions about where to spend their evenings."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Gymkhana',
'Mayfair',
'Power Lunch',
'The Albemarle Street Indian restaurant has held a Michelin star since opening in 2013 and remains the finest Indian cooking in London — a statement that generates debate only from people who have not eaten the kid goat methi keema. The colonial-club aesthetic (ceiling fans, rattan, dark teak) is a deliberate frame for food that is doing something far more ambitious. The lunch is a serious occasion. The bar makes the best gimlet in Mayfair.',
51.5094, -0.1427,
NULL,
4,
'{"men": {"brands": ["Canali", "Reiss", "IWC", "Church''s"], "outfit": {"top": "A smart blazer or jacket — Gymkhana is Michelin-starred and Mayfair and the room warrants it", "bottom": "Dark tailored trousers", "shoes": "Leather shoes in tan or black", "bag": "A slim briefcase if it''s a working lunch", "accessories": "IWC or Rolex, minimal additional jewelry"}, "color_palette": "Navy, dark tan, cream — Mayfair power lunch in a room with better spicing than its neighbours", "budget_dupe": "A quality blazer and pressed dark trousers from anywhere. Gymkhana rewards the quality of your appetite and your conversation as much as your clothes."}, "women": {"brands": ["Victoria Beckham", "Roland Mouret", "Cartier", "Aquazzura"], "outfit": {"top": "A structured blazer or dress in a jewel tone — deep teal, forest green, deep red — responding to the warm teak and rattan interior", "bottom": "Tailored trousers or a structured knee-length dress", "shoes": "A pointed-toe heel or clean flat in leather", "bag": "A structured tote or ladybag for the working lunch", "accessories": "A significant piece of jewelry — Gymkhana''s colonial-club aesthetic rewards gold and colour"}, "color_palette": "Deep teal, forest green, deep red, gold — the colours of a properly decorated colonial club, worn with modern conviction", "budget_dupe": "Reiss or Hobbs for the tailored blazer and dress. One real piece of jewelry. Gymkhana''s kid goat methi keema will make every other lunch feel insufficient."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Maison François',
'St James''s',
'Continental',
'The St James''s Street brasserie from François O''Neill opened in 2020 and immediately became the best all-day restaurant in that part of London: a warm, wood-panelled room, an outstanding wine list, and a menu that executes French brasserie food with the precision of somewhere that has been doing it for decades. The bar downstairs (Frank''s) is a serious late-night destination. The tarte tatin is essential.',
51.5070, -0.1388,
NULL,
3,
'{"men": {"brands": ["Drake''s", "Favourbrook", "Rolex", "Grenson"], "outfit": {"top": "A quality blazer or a fine shirt in a warm tone — Maison François is smart casual St James''s rather than suit-required", "bottom": "Dark slim trousers or premium dark jeans", "shoes": "Leather loafers or a quality brogue", "bag": "Nothing", "accessories": "Rolex Explorer or a vintage watch, a simple pocket square if wearing a blazer"}, "color_palette": "Camel, dark navy, warm cream — the French brasserie palette that St James''s somehow does better than anywhere else", "budget_dupe": "A quality blazer and good jeans from anywhere. Maison François is warm and excellent and does not require a Savile Row suit to appreciate."}, "women": {"brands": ["Sézane", "Isabel Marant", "Astley Clarke", "Carel Paris"], "outfit": {"top": "A French-inflected piece — a Breton stripe, a quality silk blouse, a wrap dress in a warm print", "bottom": "Straight-leg dark jeans or tailored trousers", "shoes": "Clean leather loafers or ankle boots", "bag": "A quality leather crossbody or structured tote", "accessories": "Gold hoops, a simple ring, a thin bracelet — the French approach applies in a French brasserie"}, "color_palette": "Warm white, navy, terracotta, camel — Maison François is the most Parisian room in St James''s, which is an extraordinary achievement", "budget_dupe": "Sézane for the French-inflected pieces. A good brasserie forgives everything and the tarte tatin will be the most important thing at the table."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Liberty London',
'Soho',
'Luxury Retail',
'The 1925 mock-Tudor building — constructed from the timber of two ships, HMS Impregnable and HMS Hindustan — contains one of the most beautiful retail interiors in the world. The central courtyard, the carved galleries, the galleried floors — and then the Liberty print fabrics, the perfume hall, the beauty department, and the haberdashery floor where serious people spend serious time. Enter through the Great Marlborough Street facade. Take the stairs, not the lift.',
51.5149, -0.1394,
NULL,
2,
'{"men": {"brands": ["Liberty Own Brand", "Drake''s", "Barbour", "Margaret Howell"], "outfit": {"top": "A considered piece in a Liberty print or something that acknowledges the building''s aesthetic — a quality flannel shirt or a fine merino", "bottom": "Dark slim trousers or cord in tobacco", "shoes": "Leather Chelsea boots or a quality brogue", "bag": "A Liberty paper bag from a previous visit, carried as a deliberate cultural signal", "accessories": "A mechanical watch, a simple signet ring"}, "color_palette": "Tobacco, navy, forest green, Liberty print — the building''s own palette is the strongest in London retail", "budget_dupe": "Liberty''s own brand is extremely good and accessible. A Liberty print scarf or fabric purchase is the right souvenir. The building is free to enter and extraordinary."}, "women": {"brands": ["Liberty Own", "Rixo", "Temperley London", "Penelope Chilvers"], "outfit": {"top": "A Liberty print blouse or a dress that responds to floral maximalism — this is the correct building for printed silk", "bottom": "(dress) or wide-leg trousers in a warm print", "shoes": "Clean loafers or ankle boots — you will be climbing stairs", "bag": "A Liberty tote is both functional and a statement of cultural alliance", "accessories": "Simple gold earrings, a thin necklace — the building provides all necessary complexity"}, "color_palette": "Liberty floral — Tana Lawn prints in any colourway, worn with the confidence of someone who bought them here", "budget_dupe": "Liberty''s haberdashery floor will make a metre of the most beautiful fabric in London for under £40. The building itself is the most accessible luxury in central London."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Leadenhall Market',
'City of London',
'Old Money',
'The 1881 covered market designed by Horace Jones — who also designed Tower Bridge — is one of the most extraordinary Victorian commercial spaces in London. The painted iron and glass roof, the ornate columns, the cobblestone lanes between the shops and restaurants: the City of London at its most architecturally confident. Harry Potter filmed here. The pubs open at 7am for the City crowd and the wine bars fill at 12:30 precisely.',
51.5131, -0.0838,
NULL,
2,
'{"men": {"brands": ["City of London standard", "Paul Smith", "Rolex", "Loake"], "outfit": {"top": "A City suit — dark navy or charcoal, well-cut — or a blazer if it''s a weekend visit when the market is quieter and more atmospheric", "bottom": "Matching trousers for the City; dark jeans acceptable on weekends", "shoes": "Polished black or dark tan Oxfords, always", "bag": "A quality briefcase or document portfolio during the week", "accessories": "Rolex Datejust or Explorer — the City''s standard-issue watch for good reason"}, "color_palette": "Dark navy, charcoal, white — the City suit palette, unchanged since before Horace Jones built the market", "budget_dupe": "A well-fitted dark suit from anywhere. The market is free to enter and extraordinary. Loake shoes from their own sale — the cobblestones demand proper leather soles."}, "women": {"brands": ["City appropriate", "Hobbs", "Cartier", "LK Bennett"], "outfit": {"top": "A structured blazer or a City-appropriate dress — the working week crowd here are dressed seriously", "bottom": "Tailored trousers or a pencil skirt at the knee", "shoes": "Court shoes or pointed flats — cobblestones and City formality simultaneously", "bag": "A structured leather work tote", "accessories": "Simple gold jewellery, a quality watch"}, "color_palette": "Charcoal, deep navy, cream — the Victorian iron and glass roof transforms every outfit into something more significant", "budget_dupe": "A quality Hobbs blazer and tailored trousers. The market is spectacular and free. The cobblestones are worth the leather-soled shoe investment."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Royal Arcade',
'Mayfair',
'Luxury Retail',
'The 1879 covered arcade connecting Old Bond Street to Albemarle Street is smaller and less famous than Burlington Arcade and more beautiful for it. The painted ceiling, the original shop fronts, the quiet that descends even ten metres from Bond Street — it is a piece of Victorian commercial architecture that has survived intact. Charbonnel et Walker chocolates occupy one end. Walk through slowly. There is no other correct speed here.',
51.5095, -0.1416,
NULL,
3,
'{"men": {"brands": ["Charbonnel et Walker (for the chocolates)", "N.Peal", "Deakin & Francis"], "outfit": {"top": "A quality blazer or overcoat — the arcade rewards the kind of dressing that fits a Victorian covered walkway", "bottom": "Dark tailored trousers or cord", "shoes": "Polished Oxfords or suede loafers in tan", "bag": "Nothing or a paper bag from a purchase within", "accessories": "A dress watch, a simple signet ring"}, "color_palette": "Camel, dark tan, deep navy — Victorian arcade dressing in the Bond Street context", "budget_dupe": "The Royal Arcade is free to walk through. A good coat worn properly. The Charbonnel et Walker chocolate purchase is the minimum viable commitment to the space."}, "women": {"brands": ["Asprey", "Annoushka", "Charbonnel et Walker (obviously)"], "outfit": {"top": "A cashmere coat or a quality jacket — the arcade is short but the architectural quality deserves the response", "bottom": "Tailored midi skirt or straight trousers", "shoes": "A modest heel or pointed flat", "bag": "A structured bag that fits the Victorian proportions of the space", "accessories": "Pearl earrings, a thin gold chain, nothing too contemporary"}, "color_palette": "Cream, camel, pale gold — the 1879 painted ceiling dictates the colour palette and it is right", "budget_dupe": "A great coat from anywhere, worn with intention. The Royal Arcade is one of the most beautiful free spaces in London and is unknown to most people who walk Bond Street daily."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Sir John Soane''s Museum',
'Holborn',
'Intellectual',
'The house at 13 Lincoln''s Inn Fields is exactly as the architect Sir John Soane left it at his death in 1837, having passed an Act of Parliament to preserve it. The Monk''s Parlour, the Picture Room with its hinged panels concealing three times as many paintings as the walls suggest, the sarcophagus of Seti I in the basement — it is the most astonishing house museum in the world. Free entry. Open Tuesday to Saturday. Every visit reveals something new.',
51.5173, -0.1186,
NULL,
2,
'{"men": {"brands": ["Whatever communicates intellectual seriousness"], "outfit": {"top": "A considered piece — a quality corduroy blazer, a fine merino, a moleskin — the Soane Museum rewards dressing as if you''re visiting a private house", "bottom": "Dark cord or slim trousers in tobacco", "shoes": "Leather-soled shoes — the floors are significant and deserve respect", "bag": "A leather satchel or document case with something in it worth reading", "accessories": "A mechanical watch, wire-framed glasses if you wear them"}, "color_palette": "Tobacco, dark green, warm grey — the colours of a serious 19th-century interior", "budget_dupe": "The Soane is free. A quality secondhand corduroy blazer. The museum is the most concentrated architectural experience available in London at no cost."}, "women": {"brands": ["Toast", "Margaret Howell", "Hermès (scarf)", "Grenson"], "outfit": {"top": "A quality knitwear piece in a warm colour or a tailored blouse in a muted print", "bottom": "A midi A-line skirt or straight-leg cord trousers", "shoes": "Leather-soled flat shoes — the house has narrow stairs and uneven floors", "bag": "A worn leather tote with room for a notebook", "accessories": "A silk scarf, simple gold earrings, reading glasses if applicable"}, "color_palette": "Rust, sage, warm ivory, tobacco — the palette that belongs in a 19th-century house full of Egyptian sarcophagi and Hogarth paintings", "budget_dupe": "The Soane Museum is free and more extraordinary than any paid London attraction. Dress as if you''re visiting a house that demands your respect. It does."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Daunt Books',
'Marylebone',
'Intellectual',
'The Edwardian bookshop on Marylebone High Street — with its long oak galleries, skylights, and William Morris stained glass — is one of the most beautiful retail spaces in London and happens to sell books arranged by country rather than genre. The travel section in the back gallery has the quality of a private library. Browse the long back room. Buy at least one thing you didn''t plan to. The weekend crowd is exactly the right Marylebone.',
51.5236, -0.1528,
NULL,
2,
'{"men": {"brands": ["Whatever is in the book bag"], "outfit": {"top": "A quality casual piece — a fine knit, a quality Oxford shirt, a well-chosen jacket in a warm tone", "bottom": "Dark jeans or cord trousers", "shoes": "Leather-soled shoes or quality boots", "bag": "A canvas or leather tote with a book already in it — arriving at Daunt''s carrying a book is the highest form of social proof", "accessories": "A mechanical watch, reading glasses if applicable"}, "color_palette": "Camel, dark navy, warm grey — the Marylebone High Street Saturday palette in a building with William Morris stained glass", "budget_dupe": "The books are the investment. A good crewneck and dark jeans. Daunt''s weekend crowd is warm and intelligent and will only judge you if you arrive not intending to buy anything."}, "women": {"brands": ["Toast", "Cos", "Hermès (the scarf)", "Hunter"], "outfit": {"top": "A quality knit or a patterned blouse in a warm literary colour — rust, sage, deep burgundy", "bottom": "Straight-leg dark jeans or wide-leg cord trousers", "shoes": "Clean ankle boots or leather loafers", "bag": "A quality canvas tote — already containing something from a previous visit", "accessories": "Simple earrings, a scarf — the long back gallery is cool and the skylights are beautiful"}, "color_palette": "Rust, sage, warm ivory, deep burgundy — the colours of a serious reading life", "budget_dupe": "The books are the point and the luxury. Dress for a beautiful Edwardian bookshop on a Saturday morning in Marylebone. The stained glass will make everything look better."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Maison Assouline',
'Piccadilly',
'Luxury Retail',
'The Assouline flagship at 196A Piccadilly is the most beautiful bookshop in London: floor-to-ceiling shelves of the publisher''s oversized art, fashion, and cultural books, a fireplace, a café serving coffee and Champagne, and the general atmosphere of a private library to which you have unexpectedly been admitted. The books are genuinely beautiful objects. Buy one. Or sit by the fireplace and understand what a bookshop can be.',
51.5087, -0.1344,
NULL,
3,
'{"men": {"brands": ["Brunello Cucinelli", "Loro Piana", "Rolex", "Common Projects"], "outfit": {"top": "A cashmere crewneck or a quality unstructured blazer — Assouline is Piccadilly luxury that rewards understated dressing", "bottom": "Dark slim trousers or premium dark jeans", "shoes": "Clean leather loafers or minimal white shoes", "bag": "Nothing or a very slim document holder", "accessories": "Rolex or a design-forward watch, no excessive jewelry"}, "color_palette": "Stone, camel, cream — the luxury bookshop palette where the books provide all necessary colour", "budget_dupe": "Clean basics in a neutral palette from anywhere. Maison Assouline''s atmosphere is generous and the fireplace is free to sit by."}, "women": {"brands": ["The Row", "Celine", "Cartier", "Bottega Veneta"], "outfit": {"top": "A silk blouse or cashmere in stone or ivory — the Assouline books provide the colour, your outfit provides the frame", "bottom": "Wide-leg trousers or a tailored skirt in a neutral tone", "shoes": "Clean leather loafers or a minimal flat", "bag": "A quality structured bag without excessive branding", "accessories": "Simple gold earrings, a thin chain, one good ring"}, "color_palette": "Ivory, stone, camel — a bookshop that looks like this warrants the quietest possible palette", "budget_dupe": "Clean neutrals from COS or Arket. A copy of an Assouline book carried under your arm is both a cultural signal and a significant prop."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Aquavit London',
'St James''s',
'Continental',
'The London outpost of the New York and Stockholm institution occupies the same Carlton Street building as The Haymarket Hotel and serves Nordic cuisine at a Michelin-starred level. Gravlax, herring, smørrebrød, and a tasting menu that takes Scandinavian food as seriously as it deserves. The room is clean, pale-toned, and lit with Nordic restraint. The aquavit trolley is mandatory.',
51.5073, -0.1365,
NULL,
4,
'{"men": {"brands": ["Norse Projects", "Our Legacy", "Nomos", "Saturdays NYC"], "outfit": {"top": "A clean Scandinavian-influenced piece — a quality rollneck in grey or navy, or an unstructured blazer in muted tone", "bottom": "Dark slim trousers or premium dark jeans", "shoes": "Clean minimal shoes — white or black leather", "bag": "Nothing or a very slim portfolio", "accessories": "Nomos Tangente or a design-conscious watch, minimal jewelry"}, "color_palette": "Pale grey, navy, clean white — Nordic restraint in a St James''s context", "budget_dupe": "Norse Projects or Cos for the clean Scandinavian aesthetic. Aquavit London rewards understated dressing at any price point."}, "women": {"brands": ["Toteme", "Aesop (the scent)", "Georg Jensen", "By Malene Birger"], "outfit": {"top": "A clean architectural piece — a long-sleeve minimal dress in pale grey, or a quality blouse in white or cream", "bottom": "(dress) or wide-leg trousers in pale grey or navy", "shoes": "Clean leather flats or a minimal low heel", "bag": "A structured minimal bag — Georg Jensen leather or anything without visible branding", "accessories": "Georg Jensen silver, minimal and architectural — the Nordic aesthetic is the instruction"}, "color_palette": "Pale grey, white, ice blue — the cleanest palette in St James''s dining", "budget_dupe": "COS for the clean Scandinavian minimal silhouette. Aquavit London is about flavour, precision, and restraint — your outfit should reflect these values."}}',
true),

('11111111-0000-0000-0000-000000000002',
'The Painted Hall',
'Greenwich',
'Art World',
'James Thornhill''s ceiling and wall paintings in the Old Royal Naval College hall took nineteen years to complete (1707–1726) and are the finest example of baroque decorative painting in Britain. The scale — 40,000 square feet of painted surface — is staggering. Entry is free. Lie on the viewing platform provided and look up at the ceiling properly. Understand that this was painted for sailors returning from war and is the most extraordinary free room in England.',
51.4824, -0.0093,
NULL,
1,
'{"men": {"brands": ["Whatever communicates the occasion"], "outfit": {"top": "Something considered — a quality blazer or coat that acknowledges you are visiting one of the finest painted interiors in the world", "bottom": "Dark trousers or jeans", "shoes": "Leather-soled shoes — the floor of the Painted Hall is as significant as the ceiling", "bag": "A tote with room for a guidebook", "accessories": "A watch, nothing more required"}, "color_palette": "Navy, charcoal, white — the ceiling is gold and crimson and baroque and your outfit should not compete", "budget_dupe": "The Painted Hall is free. A clean, considered outfit from anywhere. Lying on the viewing platform looking up at 40,000 square feet of Thornhill''s baroque painting is the most democratic luxury in Britain."}, "women": {"brands": ["Any, worn thoughtfully"], "outfit": {"top": "A structured jacket or coat — the scale of the Painted Hall warrants a certain formality of dress", "bottom": "Tailored trousers or a structured skirt", "shoes": "Flat leather shoes — practical for the river walk and the viewing platform", "bag": "A quality tote", "accessories": "Simple and understated — the room provides all necessary visual richness"}, "color_palette": "Deep navy, cream, warm stone — colours that belong in a building begun in 1694 and completed by Wren and Hawksmoor", "budget_dupe": "Everything here is free including the ceiling. Dress as if you are visiting the finest painted room in England, because you are."}}',
true),

('11111111-0000-0000-0000-000000000002',
'Somerset House Courtyard',
'Strand',
'Art World',
'The Edmond J. Safra Fountain Court — the great courtyard of Somerset House — is one of the finest urban spaces in London: Georgian neoclassical facades on three sides, the Thames visible through the south wing, 55 fountains that are ice-skating in winter. The Courtauld Gallery is inside, containing the finest small collection of Impressionists in Britain. Tom Bastin''s restaurant and the bar serve the courtyard all year. In summer, open-air cinema. In winter, the rink.',
51.5114, -0.1170,
NULL,
2,
'{"men": {"brands": ["Drake''s", "Oliver Spencer", "Nomos", "Tricker''s"], "outfit": {"top": "A quality piece that reads as culturally engaged rather than corporate — a good jacket or a considered knit", "bottom": "Dark jeans or tailored trousers", "shoes": "Leather shoes appropriate to the season", "bag": "A canvas or leather tote — the Courtauld warrants a bag with room for a catalogue", "accessories": "A Nomos or vintage watch, a signet ring"}, "color_palette": "Warm grey, navy, camel — the Somerset House courtyard palette responds to the Georgian stone", "budget_dupe": "The Courtauld Gallery charges admission; the courtyard is free. A clean, considered outfit from anywhere. The 55 fountains and the Wren-adjacent facades will make it look like a very expensive backdrop."}, "women": {"brands": ["Ulla Johnson", "Saloni", "Monica Vinader", "Russell & Bromley"], "outfit": {"top": "A flowing dress in a warm colour for summer, or a structured coat over a quality outfit in winter", "bottom": "(dress) or tailored wide-leg trousers", "shoes": "Flat boots in winter (ice rink); clean leather sandals or loafers in summer", "bag": "A quality tote with room for the Courtauld catalogue", "accessories": "Monica Vinader gold hoops, a delicate necklace — the courtyard provides the architectural frame"}, "color_palette": "Warm stone, sage, dusty rose in summer; camel, navy, deep burgundy in winter", "budget_dupe": "The courtyard is free and one of London''s greatest public spaces. A good coat in winter, a light dress in summer. The Courtauld''s Impressionists are worth every penny of the admission."}}',
true);
